// Auto-generated from AlphA V.4.50 R3 Eng.xlsb
const QUOTE_STRUCTURE = [
  {
    id: "A",
    name: "A. DESIGN & COORDINATION",
    subs: [
      {
        name: "1. Consulting, Sales",
        items: [
          {name: "Strategy Director", unit: "Fee"},
          {name: "Account Director", unit: "Fee"},
          {name: "Project Director", unit: "Fee"},
          {name: "Project Manager", unit: "Fee"},
          {name: "Ass. Project Manager", unit: "Fee"},
          {name: "Business Affairs", unit: "Fee"},
          {name: "Agent Commission", unit: "Fee"},
          {name: "Social Contributions", unit: "Fee"},
        ]
      },
      {
        name: "2. Creative",
        items: [
          {name: "Creative Director", unit: "Fee"},
          {name: "Editorial Director", unit: "Fee"},
          {name: "IA Editorial Producer", unit: "Fee"},
          {name: "Creative Strategist/Editorial Dir.", unit: "Fee"},
          {name: "Artistic Director", unit: "Fee"},
          {name: "DA Prompt Engineer", unit: "Fee"},
          {name: "Storyboard Artist", unit: "Fee"},
          {name: "In-house Illustrator", unit: "Fee"},
          {name: "Copywriter", unit: "Fee"},
          {name: "Editorial Consultant", unit: "Fee"},
          {name: "SEO Consultant", unit: "Fee"},
          {name: "Journalist", unit: "Fee"},
          {name: "EN/FR Writer", unit: "Fee"},
          {name: "AI Writer", unit: "Fee"},
          {name: "UX Designer", unit: "Fee"},
          {name: "Web Designer", unit: "Fee"},
          {name: "Agent Commission", unit: "Fee"},
          {name: "Social Contributions", unit: "Fee"},
        ]
      },
      {
        name: "3. Business Affairs",
        items: [
          {name: "Consulting", unit: "Fee"},
          {name: "New Campaign - Std Models/Talents Rights Nego.", unit: "Fee"},
          {name: "New Campaign - Non-Std Models/Talents Rights Nego. (SAG/AFTRA, Argentina, etc.)", unit: "Fee"},
          {name: "New Campaign - Release Form Extra", unit: "Fee"},
          {name: "Re-Nego. Ext. Campaign - Std Models/Talents Rights", unit: "Fee"},
          {name: "Re-Nego. Ext. Campaign - Non-Std Models/Talents (SAG/AFTRA, Argentina, etc.)", unit: "Fee"},
          {name: "New Campaign - Rights Nego. Photographer/Director", unit: "Fee"},
          {name: "Re-Nego. Extensions - Photographer/Director", unit: "Fee"},
          {name: "Request for approval (moral right) - Photographer/Director", unit: "Fee"},
          {name: "New Campaign - Rights Nego. Illustrator/3D Artist/Company", unit: "Fee"},
          {name: "Re- Nego. Extensions - Illustrator/3D Artist/Company", unit: "Fee"},
          {name: "Profiling & Research Celebs/Influencers/KOL/Properties (films, etc.)", unit: "Fee"},
          {name: "Making contact for Celeb/Influencer/KOL/Property (film, etc.)", unit: "Contact"},
          {name: "Nego. Celeb./Influencer/KOL/Property (film, etc.)", unit: "Unit"},
          {name: "Nego. Commercially Released Music Track/Orig. Prod.", unit: "Unit"},
          {name: "Re-Nego. Extensions Commercially Released Music Track/Orig. Prod.", unit: "Unit"},
          {name: "Nego. Library Music", unit: "Unit"},
          {name: "Re-Nego. Extensions - Library Music", unit: "Unit"},
          {name: "Nego. Admin Fee - Orig. Prod. or Std Lead singer", unit: "Unit"},
          {name: "Nego. Admin Fee - Standard Voice-Over", unit: "Unit"},
          {name: "Usage Rights Management", unit: "Fee"},
          {name: "Pre-Clearance ARPP", unit: "Fee"},
          {name: "Admin Fees", unit: "Fee"},
          {name: "Miscellaneous", unit: "Fee"},
          {name: "Agent Commission", unit: "Fee"},
          {name: "Social Contributions", unit: "Fee"},
        ]
      },
    ]
  },
  {
    id: "B",
    name: "B. PRE-PRODUCTION",
    subs: [
      {
        name: "4.1a. Wages",
        items: [
          {name: "Director", unit: "Day"},
          {name: "Executive Producer", unit: "Day"},
          {name: "Line Producer", unit: "Day"},
          {name: "Production manager", unit: "Day"},
          {name: "Production Coordinator", unit: "Day"},
          {name: "Production Secretary", unit: "Day"},
          {name: "Office PA", unit: "Day"},
          {name: "1st Ass. Director", unit: "Day"},
          {name: "2nd Ass. Director", unit: "Day"},
          {name: "Researcher", unit: "Day"},
          {name: "Translator", unit: "Day"},
          {name: "Location Scout", unit: "Day"},
          {name: "Location/Unit Manager", unit: "Day"},
          {name: "Ass. Location/Unit Manager", unit: "Day"},
          {name: "Runners", unit: "Day"},
          {name: "Director's Drivers", unit: "Day"},
          {name: "Agency 's Drivers", unit: "Day"},
          {name: "Director of Photography", unit: "Day"},
          {name: "1st Ass. Camera (tests)", unit: "Day"},
          {name: "2nd Ass. Camera", unit: "Day"},
          {name: "DIT", unit: "Day"},
          {name: "Video Ass.", unit: "Day"},
          {name: "Key Grip (shoot)", unit: "Day"},
          {name: "Best Boy Grip (shoot)", unit: "Day"},
          {name: "Grip (shoot)", unit: "Day"},
          {name: "Gaffer (shoot)", unit: "Day"},
          {name: "Best Boy Electrician (shoot)", unit: "Day"},
          {name: "Electrician (shoot)", unit: "Day"},
          {name: "Production Designer", unit: "Day"},
          {name: "Art Coordinator", unit: "Day"},
          {name: "Swing Man", unit: "Day"},
          {name: "Set Dresser/Decorator", unit: "Day"},
          {name: "Prop Master", unit: "Day"},
          {name: "Head of Wardrobe", unit: "Day"},
          {name: "Costume Designer", unit: "Day"},
          {name: "Head of Costume Workshop", unit: "Day"},
          {name: "Stylist", unit: "Day"},
          {name: "Stylist's Ass.", unit: "Day"},
          {name: "Seamstress", unit: "Day"},
          {name: "Wardrobe Ass.", unit: "Day"},
          {name: "constr. Manager", unit: "Day"},
          {name: "Key Grip (constr.)", unit: "Day"},
          {name: "Gaffer (constr.)", unit: "Day"},
          {name: "Head Painter", unit: "Day"},
          {name: "Head Upholsterer", unit: "Day"},
          {name: "Head Carpenter", unit: "Day"},
          {name: "Head Sculptor", unit: "Day"},
          {name: "Head Set Metal Worker", unit: "Day"},
          {name: "Carpenter", unit: "Day"},
          {name: "Scenic", unit: "Day"},
          {name: "Head of SFX on Set", unit: "Day"},
          {name: "SFX Technician", unit: "Day"},
          {name: "Food Stylist", unit: "Day"},
          {name: "Food Stylist's Ass.", unit: "Day"},
          {name: "Makeup Artist", unit: "Day"},
          {name: "Hair Stylist", unit: "Day"},
          {name: "Makeup/Hair Ass.", unit: "Day"},
          {name: "Agent Commission", unit: "Fee"},
          {name: "Social Contributions", unit: "Fee"},
        ]
      },
      {
        name: "4.2a. Expenses",
        items: [
          {name: "Location Scouting", unit: "Fee"},
          {name: "Stills & Videos Recces", unit: "Fee"},
          {name: "Mileage Location Scout", unit: "Day"},
          {name: "Gas & Tolls", unit: "Fee"},
          {name: "Location File Pull & Research", unit: "Fee"},
          {name: "Location Scouting Digital Processing", unit: "Fee"},
          {name: "Overnight Deliveries, Messenger", unit: "Fee"},
          {name: "FTP", unit: "Fee"},
          {name: "Telephone, Mob. & Fax", unit: "Fee"},
          {name: "Misc. & Prov. for Expenses", unit: "Fee"},
          {name: "Social Contributions", unit: "Fee"},
        ]
      },
      {
        name: "4.1b. Wages / Prod Service",
        items: [
          {name: "Executive Producer", unit: "Fee"},
          {name: "Line Producer", unit: "Day"},
          {name: "Production manager", unit: "Day"},
          {name: "Production Coordinator", unit: "Day"},
          {name: "Production Secretary", unit: "Day"},
          {name: "Office PA", unit: "Day"},
          {name: "1st Ass. Director", unit: "Day"},
          {name: "2nd Ass. Director", unit: "Day"},
          {name: "Researcher", unit: "Day"},
          {name: "Translator", unit: "Day"},
          {name: "Location Scout", unit: "Day"},
          {name: "Location/Unit Manager", unit: "Day"},
          {name: "Ass. Location/Unit Manager", unit: "Day"},
          {name: "Runners", unit: "Day"},
          {name: "Director's Drivers", unit: "Day"},
          {name: "Agency 's Drivers", unit: "Day"},
          {name: "Director of Photography", unit: "Day"},
          {name: "1st Ass. Camera (tests)", unit: "Day"},
          {name: "2nd Ass. Camera", unit: "Day"},
          {name: "DIT", unit: "Day"},
          {name: "Video Ass.", unit: "Day"},
          {name: "Key Grip (shoot)", unit: "Day"},
          {name: "Best Boy Grip (shoot)", unit: "Day"},
          {name: "Grip (shoot)", unit: "Day"},
          {name: "Gaffer (shoot)", unit: "Day"},
          {name: "Best Boy Electrician (shoot)", unit: "Day"},
          {name: "Electrician (shoot)", unit: "Day"},
          {name: "Production Designer", unit: "Day"},
          {name: "Art Coordinator", unit: "Day"},
          {name: "Swing Man", unit: "Day"},
          {name: "Set Dresser/Decorator", unit: "Day"},
          {name: "Prop Master", unit: "Day"},
          {name: "Head of Wardrobe", unit: "Day"},
          {name: "Costume Designer", unit: "Day"},
          {name: "Head of Costume Workshop", unit: "Day"},
          {name: "Stylist", unit: "Day"},
          {name: "Stylist's Ass.", unit: "Day"},
          {name: "Seamstress", unit: "Day"},
          {name: "Wardrobe Ass.", unit: "Day"},
          {name: "constr. Manager", unit: "Day"},
          {name: "Key Grip (constr.)", unit: "Day"},
          {name: "Gaffer (constr.)", unit: "Day"},
          {name: "Head Painter", unit: "Day"},
          {name: "Head Upholsterer", unit: "Day"},
          {name: "Head Carpenter", unit: "Day"},
          {name: "Head Sculptor", unit: "Day"},
          {name: "Head Set Metal Worker", unit: "Day"},
          {name: "Carpenter", unit: "Day"},
          {name: "Scenic", unit: "Day"},
          {name: "Head of SFX on Set", unit: "Day"},
          {name: "SFX Technician", unit: "Day"},
          {name: "Food Stylist", unit: "Day"},
          {name: "Food Stylist's Ass.", unit: "Day"},
          {name: "Makeup Artist", unit: "Day"},
          {name: "Hair Stylist", unit: "Day"},
          {name: "Makeup/Hair Ass.", unit: "Day"},
          {name: "Agent Commission (Serv.)", unit: "Fee"},
          {name: "Social Contributions (Serv.)", unit: "Fee"},
        ]
      },
      {
        name: "4.2b. Expenses (prep & recces)/Prod Service",
        items: [
          {name: "Location Scouting", unit: "Fee"},
          {name: "Stills & Videos Recces", unit: "Fee"},
          {name: "Mileage Location Scout", unit: "Day"},
          {name: "Gas & Tolls", unit: "Fee"},
          {name: "Location File Pull & Research", unit: "Fee"},
          {name: "Location Scouting Digital Processing", unit: "Fee"},
          {name: "Overnight Deliveries, Messenger", unit: "Fee"},
          {name: "FTP", unit: "Fee"},
          {name: "Telephone, Mob. & Fax", unit: "Fee"},
          {name: "Misc. & Prov. for Expenses", unit: "Fee"},
          {name: "Social Contributions (Serv.)", unit: "Fee"},
        ]
      },
      {
        name: "4.3. Miscellaneous (incl. Post-production)",
        items: [
          {name: "Translations", unit: "Fee"},
          {name: "Storyboard", unit: "Fee"},
          {name: "Research & Doc.", unit: "Fee"},
          {name: "Stock-shots", unit: "Unit"},
          {name: "Photos, Polaroid's", unit: "Fee"},
          {name: "Video Tests", unit: "Unit"},
          {name: "Video Conferences", unit: "Hour"},
          {name: "Helicopter", unit: "Fee"},
          {name: "Director's Agent Coordination", unit: "Fee"},
          {name: "Director's Agent Expenses", unit: "Fee"},
          {name: "Pre Post-production", unit: "Fee"},
          {name: "Previz", unit: "Fee"},
          {name: "Animatic", unit: "Fee"},
          {name: "Visual Development", unit: "Fee"},
          {name: "AI Creative Design", unit: "Fee"},
          {name: "Social Contributions (Serv.)", unit: "Fee"},
          {name: "Social Contributions", unit: "Fee"},
        ]
      },
      {
        name: "4.4. Casting 1",
        items: [
          {name: "Casting Director", unit: "Day"},
          {name: "Casting Director (add. roles)", unit: "Day"},
          {name: "Extras Casting Director", unit: "Day"},
          {name: "Video Ass.", unit: "Day"},
          {name: "Call-back", unit: "Day"},
          {name: "Casting Studio", unit: "Day"},
          {name: "Video Equipment", unit: "Day"},
          {name: "Casting Editing", unit: "Day"},
          {name: "FTP", unit: "Fee"},
          {name: "Social Contributions (Serv.)", unit: "Fee"},
          {name: "Social Contributions", unit: "Fee"},
        ]
      },
      {
        name: "4.5. Casting 2",
        items: [
          {name: "Casting Director", unit: "Day"},
          {name: "Casting Director (add. roles)", unit: "Day"},
          {name: "Extras Casting Director", unit: "Day"},
          {name: "Video Ass.", unit: "Day"},
          {name: "Call-back", unit: "Day"},
          {name: "Casting Studio", unit: "Day"},
          {name: "Video Equipment", unit: "Day"},
          {name: "Casting Editing", unit: "Day"},
          {name: "FTP", unit: "Fee"},
          {name: "Social Contributions (Serv.)", unit: "Fee"},
          {name: "Social Contributions", unit: "Fee"},
        ]
      },
    ]
  },
  {
    id: "B",
    name: "B. TALENT",
    subs: [
      {
        name: "5.1. Actors",
        items: [
          {name: "Principals T10", unit: "Day"},
          {name: "Secondary Roles T8", unit: "Day"},
          {name: "Call-back", unit: "Day"},
          {name: "Travel Days", unit: "Day"},
          {name: "Fitting Fee", unit: "Day"},
          {name: "Agent Commission (Serv.)", unit: "Fee"},
          {name: "Agent Commission", unit: "Fee"},
          {name: "Social Contributions (Serv.)", unit: "Fee"},
          {name: "Social Contributions", unit: "Fee"},
        ]
      },
      {
        name: "5.2. Models",
        items: [
          {name: "Model T7", unit: "Day"},
          {name: "Model T8", unit: "Day"},
          {name: "Model T9", unit: "Day"},
          {name: "Model T10", unit: "Day"},
          {name: "Model T12", unit: "Day"},
          {name: "Model T15", unit: "Day"},
          {name: "Model T20", unit: "Day"},
          {name: "Model T25", unit: "Day"},
          {name: "Model T30", unit: "Day"},
          {name: "Model T35", unit: "Day"},
          {name: "Model T40", unit: "Day"},
          {name: "Model T50", unit: "Day"},
          {name: "Model (hands, feet, body…)", unit: "Day"},
          {name: "Call-back", unit: "Day"},
          {name: "Travel Days", unit: "Day"},
          {name: "Fitting Fee", unit: "Day"},
          {name: "Agent Commission (Serv.)", unit: "Fee"},
          {name: "Agent Commission", unit: "Fee"},
          {name: "Social Contributions (Serv.)", unit: "Fee"},
          {name: "Social Contributions", unit: "Fee"},
        ]
      },
      {
        name: "5.3. Extras & Small Parts",
        items: [
          {name: "Extras", unit: "Day"},
          {name: "Featured Extras", unit: "Day"},
          {name: "Stand-ins", unit: "Day"},
          {name: "Hand Model", unit: "Day"},
          {name: "Fitting Fee", unit: "Day"},
          {name: "Body Double", unit: "Day"},
          {name: "Agent Commission (Serv.)", unit: "Fee"},
          {name: "Agent Commission", unit: "Fee"},
          {name: "Social Contributions (Serv.)", unit: "Fee"},
          {name: "Social Contributions", unit: "Fee"},
        ]
      },
      {
        name: "5.4. Others",
        items: [
          {name: "Children", unit: "Day"},
          {name: "Parent", unit: "Day"},
          {name: "Fitting Fee", unit: "Day"},
          {name: "Chaperon", unit: "Day"},
          {name: "Travel Days", unit: "Day"},
          {name: "Medical Check-up", unit: "Fee"},
          {name: "Choreographer", unit: "Day"},
          {name: "Dancer", unit: "Day"},
          {name: "Coach", unit: "Day"},
          {name: "Precision Driver", unit: "Day"},
          {name: "Stunt", unit: "Day"},
          {name: "Animals (+ Wrangler)", unit: "Day"},
          {name: "Technical Adviser", unit: "Day"},
          {name: "Agent Commission (Serv.)", unit: "Fee"},
          {name: "Agent Commission", unit: "Fee"},
          {name: "Social Contributions (Serv.)", unit: "Fee"},
          {name: "Social Contributions", unit: "Fee"},
        ]
      },
      {
        name: "5.5. Rights",
        items: [
          {name: "Talents Usage Fee", unit: "Fee"},
          {name: "Models Usage Fee", unit: "Fee"},
          {name: "Child Usage Fee", unit: "Fee"},
          {name: "Usage Fee", unit: "Fee"},
          {name: "Agent Commission (Serv.)", unit: "Fee"},
          {name: "Agent Commission", unit: "Fee"},
          {name: "Social Contributions (Serv.)", unit: "Fee"},
          {name: "Social Contributions", unit: "Fee"},
        ]
      },
    ]
  },
  {
    id: "B",
    name: "B. SHOOTING CREW",
    subs: [
      {
        name: "6.1. Director",
        items: [
          {name: "Director", unit: "Day"},
          {name: "Director (rights)", unit: "Fee"},
          {name: "Photographer", unit: "Day"},
          {name: "Photographer (rights)", unit: "Fee"},
          {name: "Agent Commission", unit: "Fee"},
        ]
      },
      {
        name: "6.2. Production Unit",
        items: [
          {name: "Executive Producer", unit: "Fee"},
          {name: "Line Producer", unit: "Day"},
          {name: "Production Manager", unit: "Day"},
          {name: "Production Coordinator", unit: "Day"},
          {name: "Production Secretary", unit: "Day"},
          {name: "Production Ass.", unit: "Day"},
          {name: "Production Ass. #2", unit: "Day"},
          {name: "Location/Unit Manager", unit: "Day"},
          {name: "Ass. Location/Unit Manager", unit: "Day"},
          {name: "Runners", unit: "Day"},
          {name: "Chaperon", unit: "Day"},
          {name: "Runner/Marking & Supply", unit: "Day"},
          {name: "Canteen Chief", unit: "Day"},
          {name: "Director's Drivers", unit: "Day"},
          {name: "Agency's Drivers", unit: "Day"},
          {name: "Agent Commission", unit: "Fee"},
        ]
      },
      {
        name: "6.3. Director's Unit",
        items: [
          {name: "1st Ass. Director", unit: "Day"},
          {name: "2nd Ass. Director", unit: "Day"},
          {name: "Runners", unit: "Day"},
          {name: "Script/Continuity", unit: "Day"},
          {name: "Extras Captain", unit: "Day"},
          {name: "Ass. Extras Captain", unit: "Day"},
          {name: "Agent Commission", unit: "Fee"},
        ]
      },
      {
        name: "6.4. Camera",
        items: [
          {name: "Director of Photography", unit: "Day"},
          {name: "Camera Operator", unit: "Day"},
          {name: "1st Ass. Camera", unit: "Day"},
          {name: "2nd Ass. Camera", unit: "Day"},
          {name: "Ass. Photographer", unit: "Day"},
          {name: "VTR Technician", unit: "Day"},
          {name: "VTR Ass.", unit: "Day"},
          {name: "Steadicamer", unit: "Day"},
          {name: "Remote Tools' Operator", unit: "Day"},
          {name: "Still Photographer", unit: "Day"},
          {name: "DIT", unit: "Day"},
          {name: "Data Manager", unit: "Day"},
          {name: "Phantom Operator", unit: "Day"},
          {name: "Phantom Operator's Ass.", unit: "Day"},
          {name: "Digital Operator (photo)", unit: "Day"},
          {name: "Agent Commission", unit: "Fee"},
        ]
      },
      {
        name: "6.5. Sound",
        items: [
          {name: "Sound Engineer", unit: "Day"},
          {name: "Sound Ass.", unit: "Day"},
          {name: "Agent Commission", unit: "Fee"},
        ]
      },
      {
        name: "6.6. Grips, Electricians",
        items: [
          {name: "Key Grip", unit: "Day"},
          {name: "Best Boy Grip", unit: "Day"},
          {name: "Grip", unit: "Day"},
          {name: "Crane Grip", unit: "Day"},
          {name: "Crane Technician (Technocrane/Louma)", unit: "Day"},
          {name: "Spinner Technician", unit: "Day"},
          {name: "Hot Head Technician", unit: "Day"},
          {name: "Wescam Technician", unit: "Day"},
          {name: "Gaffer", unit: "Day"},
          {name: "Best Boy Electrician", unit: "Day"},
          {name: "Electrician", unit: "Day"},
          {name: "Generator Operator", unit: "Day"},
          {name: "Electricians/Grips Pre-light", unit: "Day"},
          {name: "Load/Unload", unit: "Day"},
          {name: "Trailer Dressing Driver", unit: "Day"},
          {name: "Agent Commission", unit: "Fee"},
        ]
      },
      {
        name: "6.7. Miscellaneous",
        items: [
          {name: "Drone Operator", unit: "Day"},
          {name: "Precision Driver/Heli. Pilot", unit: "Day"},
          {name: "Camera Car Driver", unit: "Day"},
          {name: "Truck Driver Hero Car", unit: "Day"},
          {name: "Drivers", unit: "Day"},
          {name: "Precision Driver", unit: "Day"},
          {name: "Arm Operator Russian Arm", unit: "Day"},
          {name: "Mechanic Russian Arm", unit: "Day"},
          {name: "Camera Operator Russian Arm", unit: "Day"},
          {name: "Space Saver", unit: "Day"},
          {name: "Production Runners", unit: "Day"},
          {name: "Nurse/1st Aid/Medical Referent", unit: "Day"},
          {name: "Day Security", unit: "Day"},
          {name: "Night Security", unit: "Day"},
          {name: "Security Personel for Exteriors", unit: "Day"},
          {name: "Agent Commission", unit: "Fee"},
        ]
      },
      {
        name: "6.8. Art department",
        items: [
          {name: "Production Designer", unit: "Day"},
          {name: "Lead Man", unit: "Day"},
          {name: "2nd Ass. Prod. Designer", unit: "Day"},
          {name: "3rd Ass. Prod. Designer", unit: "Day"},
          {name: "Ass. Prod. Designer", unit: "Day"},
          {name: "Swing Man", unit: "Day"},
          {name: "Set Dresser/Designer", unit: "Day"},
          {name: "Set Dresser", unit: "Day"},
          {name: "Set Illustrator", unit: "Day"},
          {name: "Props Master", unit: "Day"},
          {name: "Props Ass.", unit: "Day"},
          {name: "Head of SFX", unit: "Day"},
          {name: "SFX Technician", unit: "Day"},
          {name: "Car Detailer", unit: "Day"},
          {name: "Art Department Driver", unit: "Day"},
          {name: "Agent Commission", unit: "Fee"},
        ]
      },
      {
        name: "6.9. Stylism",
        items: [
          {name: "Stylist", unit: "Day"},
          {name: "Ass. Costume Designer/Stylist", unit: "Day"},
          {name: "Costume Designer", unit: "Day"},
          {name: "Head of Wardrobe", unit: "Day"},
          {name: "Head of Costume Workshop", unit: "Day"},
          {name: "Wardrobe", unit: "Day"},
          {name: "Seamstress", unit: "Day"},
          {name: "Wardrobe Ass.", unit: "Day"},
          {name: "Food Stylist", unit: "Day"},
          {name: "Food Stylist Ass.", unit: "Day"},
          {name: "Food Stylist SFX", unit: "Day"},
          {name: "Agent Commission", unit: "Fee"},
        ]
      },
      {
        name: "6.10. Makeup & Hair",
        items: [
          {name: "Makeup Artist", unit: "Day"},
          {name: "Makeup", unit: "Day"},
          {name: "Makeup Ass.", unit: "Day"},
          {name: "Makeup Artist SFX", unit: "Day"},
          {name: "Hair Stylist", unit: "Day"},
          {name: "Hairdresser", unit: "Day"},
          {name: "Hair Ass.", unit: "Day"},
          {name: "Wig Maker", unit: "Day"},
          {name: "Manicure/Nail Artist", unit: "Day"},
          {name: "Manicure Ass.", unit: "Day"},
          {name: "Agent Commission", unit: "Fee"},
        ]
      },
      {
        name: "6.11. Studio",
        items: [
          {name: "constr. Manager", unit: "Day"},
          {name: "constr. Grip", unit: "Day"},
          {name: "Key Grip", unit: "Day"},
          {name: "Best Boy Grip", unit: "Day"},
          {name: "Grip", unit: "Day"},
          {name: "Head Painter", unit: "Day"},
          {name: "Best Boy Painter", unit: "Day"},
          {name: "Painter", unit: "Day"},
          {name: "Sign Writer", unit: "Day"},
          {name: "Wood Graining & Patina Painter", unit: "Day"},
          {name: "Scenic Artist", unit: "Day"},
          {name: "Head Upholsterer", unit: "Day"},
          {name: "Setupholsterer", unit: "Day"},
          {name: "Head Carpenter", unit: "Day"},
          {name: "Best Boy Carpenter", unit: "Day"},
          {name: "Carpenter", unit: "Day"},
          {name: "Head Sculptor", unit: "Day"},
          {name: "Sculptor", unit: "Day"},
          {name: "Plumber", unit: "Day"},
          {name: "Mason", unit: "Day"},
          {name: "Visual Artist", unit: "Day"},
          {name: "Gaffer", unit: "Day"},
          {name: "Best Boy Electrician", unit: "Day"},
          {name: "Electrician", unit: "Day"},
          {name: "Head Set Metal Worker", unit: "Day"},
          {name: "Set Metal Worker", unit: "Day"},
          {name: "Set Carpenter", unit: "Day"},
          {name: "Head Plasterer", unit: "Day"},
          {name: "Best Boy Plasterer", unit: "Day"},
          {name: "Set Plasterer", unit: "Day"},
          {name: "Set Carpenter Woodcarver", unit: "Day"},
          {name: "Model Maker", unit: "Day"},
          {name: "Agent Commission", unit: "Fee"},
        ]
      },
      {
        name: "6.12. Locations",
        items: [
          {name: "constr. Manager", unit: "Day"},
          {name: "constr. Grip", unit: "Day"},
          {name: "Key Grip", unit: "Day"},
          {name: "Best Boy Grip", unit: "Day"},
          {name: "Grip", unit: "Day"},
          {name: "Head Painter", unit: "Day"},
          {name: "Best Boy Painter", unit: "Day"},
          {name: "Painter", unit: "Day"},
          {name: "Sign Writer", unit: "Day"},
          {name: "Wood Graining & Patina Painter", unit: "Day"},
          {name: "Scenic Artist", unit: "Day"},
          {name: "Head Upholsterer", unit: "Day"},
          {name: "Setupholsterer", unit: "Day"},
          {name: "Head Carpenter", unit: "Day"},
          {name: "Best Boy Carpenter", unit: "Day"},
          {name: "Carpenter", unit: "Day"},
          {name: "Head Sculptor", unit: "Day"},
          {name: "Sculptor", unit: "Day"},
          {name: "Plumber", unit: "Day"},
          {name: "Mason", unit: "Day"},
          {name: "Visual Artist", unit: "Day"},
          {name: "Gaffer", unit: "Day"},
          {name: "Best Boy Electrician", unit: "Day"},
          {name: "Electrician", unit: "Day"},
          {name: "Head Set Metal Worker", unit: "Day"},
          {name: "Set Metal Worker", unit: "Day"},
          {name: "Set Carpenter", unit: "Day"},
          {name: "Head Plasterer", unit: "Day"},
          {name: "Best Boy Plasterer", unit: "Day"},
          {name: "Set Plasterer", unit: "Day"},
          {name: "Set Carpenter Woodcarver", unit: "Day"},
          {name: "Model Maker", unit: "Day"},
          {name: "Agent Commission", unit: "Fee"},
        ]
      },
      {
        name: "6.13. Others",
        items: [
          {name: "Drivers Overtime Hours", unit: "Fee"},
          {name: "Overtime Hours", unit: "Fee"},
          {name: "Offset Meal Time Penalties (Covid)", unit: "Fee"},
          {name: "Social Contributions Dir.", unit: "Fee"},
          {name: "Social Contributions Crew", unit: "Fee"},
        ]
      },
    ]
  },
  {
    id: "B",
    name: "B. SHOOTING CREW PROD SERVICE",
    subs: [
      {
        name: "7.1. Director",
        items: [
          {name: "Director", unit: "Day"},
          {name: "Director (rights)", unit: "Fee"},
          {name: "Photographer", unit: "Day"},
          {name: "Photographer (rights)", unit: "Fee"},
          {name: "Agent Commission (Serv.)", unit: "Fee"},
        ]
      },
      {
        name: "7.2. Production Unit",
        items: [
          {name: "Executive Producer", unit: "Day"},
          {name: "Line Producer", unit: "Day"},
          {name: "Production Manager", unit: "Day"},
          {name: "Production Coordinator", unit: "Day"},
          {name: "Production Secretary", unit: "Day"},
          {name: "Production Ass.", unit: "Day"},
          {name: "Production Ass. #2", unit: "Day"},
          {name: "Location/Unit Manager", unit: "Day"},
          {name: "Ass. Location/Unit Manager", unit: "Day"},
          {name: "Runners", unit: "Day"},
          {name: "Chaperon", unit: "Day"},
          {name: "Runner/Marking & Supply", unit: "Day"},
          {name: "Canteen Chief", unit: "Day"},
          {name: "Director's Drivers", unit: "Day"},
          {name: "Agency's Drivers", unit: "Day"},
          {name: "Agent Commission (Serv.)", unit: "Fee"},
        ]
      },
      {
        name: "7.3. Director's Unit",
        items: [
          {name: "1st Ass. Director", unit: "Day"},
          {name: "2nd Ass. Director", unit: "Day"},
          {name: "Runners", unit: "Day"},
          {name: "Script/Continuity", unit: "Day"},
          {name: "Extras Captain", unit: "Day"},
          {name: "Ass. Extras Captain", unit: "Day"},
          {name: "Agent Commission (Serv.)", unit: "Fee"},
        ]
      },
      {
        name: "7.4. Camera",
        items: [
          {name: "Director of Photography", unit: "Day"},
          {name: "Camera Operator", unit: "Day"},
          {name: "1st Ass. Camera", unit: "Day"},
          {name: "2nd Ass. Camera", unit: "Day"},
          {name: "Ass. Photographer", unit: "Day"},
          {name: "VTR Technician", unit: "Day"},
          {name: "VTR Ass.", unit: "Day"},
          {name: "Steadicamer", unit: "Day"},
          {name: "Remote Tools' Operator", unit: "Day"},
          {name: "Still Photographer", unit: "Day"},
          {name: "DIT", unit: "Day"},
          {name: "Data Manager", unit: "Day"},
          {name: "Phantom Operator", unit: "Day"},
          {name: "Phantom Operator's Ass.", unit: "Day"},
          {name: "Digital Operator (photo)", unit: "Day"},
          {name: "Agent Commission (Serv.)", unit: "Fee"},
        ]
      },
      {
        name: "7.5. Sound",
        items: [
          {name: "Sound Engineer", unit: "Day"},
          {name: "Sound Ass.", unit: "Day"},
          {name: "Agent Commission (Serv.)", unit: "Fee"},
        ]
      },
      {
        name: "7.6. Grips, Electricians",
        items: [
          {name: "Key Grip", unit: "Day"},
          {name: "Best Boy Grip", unit: "Day"},
          {name: "Grip", unit: "Day"},
          {name: "Crane Grip", unit: "Day"},
          {name: "Crane Technician (Technocrane/Louma)", unit: "Day"},
          {name: "Spinner Technician", unit: "Day"},
          {name: "Hot Head Technician", unit: "Day"},
          {name: "Wescam Technician", unit: "Day"},
          {name: "Gaffer", unit: "Day"},
          {name: "Best Boy Electrician", unit: "Day"},
          {name: "Electrician", unit: "Day"},
          {name: "Generator Operator", unit: "Day"},
          {name: "Electricians/Grips Pre-light", unit: "Day"},
          {name: "Load/Unload", unit: "Day"},
          {name: "Trailer Dressing Driver", unit: "Day"},
          {name: "Agent Commission (Serv.)", unit: "Fee"},
        ]
      },
      {
        name: "7.7. Miscellaneous",
        items: [
          {name: "Drone Operator", unit: "Day"},
          {name: "Precision Driver/Heli. Pilot", unit: "Day"},
          {name: "Camera Car Driver", unit: "Day"},
          {name: "Truck Driver Hero Car", unit: "Day"},
          {name: "Drivers", unit: "Day"},
          {name: "Precision Driver", unit: "Day"},
          {name: "Arm Operator Russian Arm", unit: "Day"},
          {name: "Mechanic Russian Arm", unit: "Day"},
          {name: "Camera Operator Russian Arm", unit: "Day"},
          {name: "Space Saver", unit: "Day"},
          {name: "Production Runners", unit: "Day"},
          {name: "Nurse/1st Aid/Medical Referent", unit: "Day"},
          {name: "Day Security", unit: "Day"},
          {name: "Night Security", unit: "Day"},
          {name: "Security Personel for Exteriors", unit: "Day"},
          {name: "Agent Commission (Serv.)", unit: "Fee"},
        ]
      },
      {
        name: "7.8. Art department",
        items: [
          {name: "Production Designer", unit: "Day"},
          {name: "Lead Man", unit: "Day"},
          {name: "2nd Ass. Prod. Designer", unit: "Day"},
          {name: "3rd Ass. Prod. Designer", unit: "Day"},
          {name: "Ass. Prod. Designer", unit: "Day"},
          {name: "Swing Man", unit: "Day"},
          {name: "Set Dresser/Designer", unit: "Day"},
          {name: "Set Dresser", unit: "Day"},
          {name: "Set Illustrator", unit: "Day"},
          {name: "Props Master", unit: "Day"},
          {name: "Props Ass.", unit: "Day"},
          {name: "Head of SFX", unit: "Day"},
          {name: "SFX Technician", unit: "Day"},
          {name: "Car Detailer", unit: "Day"},
          {name: "Art Department Driver", unit: "Day"},
          {name: "Agent Commission (Serv.)", unit: "Fee"},
        ]
      },
      {
        name: "7.9. Stylism",
        items: [
          {name: "Stylist", unit: "Day"},
          {name: "Ass. Costume Designer/Stylist", unit: "Day"},
          {name: "Costume Designer", unit: "Day"},
          {name: "Head of Wardrobe", unit: "Day"},
          {name: "Head of Costume Workshop", unit: "Day"},
          {name: "Wardrobe", unit: "Day"},
          {name: "Seamstress", unit: "Day"},
          {name: "Wardrobe Ass.", unit: "Day"},
          {name: "Food Stylist", unit: "Day"},
          {name: "Food Stylist Ass.", unit: "Day"},
          {name: "Food Stylist SFX", unit: "Day"},
          {name: "Agent Commission (Serv.)", unit: "Fee"},
        ]
      },
      {
        name: "7.10. Makeup & Hair",
        items: [
          {name: "Makeup Artist", unit: "Day"},
          {name: "Makeup", unit: "Day"},
          {name: "Makeup Ass.", unit: "Day"},
          {name: "Makeup Artist SFX", unit: "Day"},
          {name: "Hair Stylist", unit: "Day"},
          {name: "Hairdresser", unit: "Day"},
          {name: "Hair Ass.", unit: "Day"},
          {name: "Wig Maker", unit: "Day"},
          {name: "Manicure/Nail Artist", unit: "Day"},
          {name: "Manicure Ass.", unit: "Day"},
          {name: "Agent Commission (Serv.)", unit: "Fee"},
        ]
      },
      {
        name: "7.11. Studio",
        items: [
          {name: "constr. Manager", unit: "Day"},
          {name: "constr. Grip", unit: "Day"},
          {name: "Key Grip", unit: "Day"},
          {name: "Best Boy Grip", unit: "Day"},
          {name: "Grip", unit: "Day"},
          {name: "Head Painter", unit: "Day"},
          {name: "Best Boy Painter", unit: "Day"},
          {name: "Painter", unit: "Day"},
          {name: "Sign Writer", unit: "Day"},
          {name: "Wood Graining & Patina Painter", unit: "Day"},
          {name: "Scenic Artist", unit: "Day"},
          {name: "Head Upholsterer", unit: "Day"},
          {name: "Setupholsterer", unit: "Day"},
          {name: "Head Carpenter", unit: "Day"},
          {name: "Best Boy Carpenter", unit: "Day"},
          {name: "Carpenter", unit: "Day"},
          {name: "Head Sculptor", unit: "Day"},
          {name: "Sculptor", unit: "Day"},
          {name: "Plumber", unit: "Day"},
          {name: "Mason", unit: "Day"},
          {name: "Visual Artist", unit: "Day"},
          {name: "Gaffer", unit: "Day"},
          {name: "Best Boy Electrician", unit: "Day"},
          {name: "Electrician", unit: "Day"},
          {name: "Head Set Metal Worker", unit: "Day"},
          {name: "Set Metal Worker", unit: "Day"},
          {name: "Set Carpenter", unit: "Day"},
          {name: "Head Plasterer", unit: "Day"},
          {name: "Best Boy Plasterer", unit: "Day"},
          {name: "Set Plasterer", unit: "Day"},
          {name: "Set Carpenter Woodcarver", unit: "Day"},
          {name: "Model Maker", unit: "Day"},
          {name: "Agent Commission (Serv.)", unit: "Fee"},
        ]
      },
      {
        name: "7.12. Locations",
        items: [
          {name: "constr. Manager", unit: "Day"},
          {name: "constr. Grip", unit: "Day"},
          {name: "Key Grip", unit: "Day"},
          {name: "Best Boy Grip", unit: "Day"},
          {name: "Grip", unit: "Day"},
          {name: "Head Painter", unit: "Day"},
          {name: "Best Boy Painter", unit: "Day"},
          {name: "Painter", unit: "Day"},
          {name: "Sign Writer", unit: "Day"},
          {name: "Wood Graining & Patina Painter", unit: "Day"},
          {name: "Scenic Artist", unit: "Day"},
          {name: "Head Upholsterer", unit: "Day"},
          {name: "Setupholsterer", unit: "Day"},
          {name: "Head Carpenter", unit: "Day"},
          {name: "Best Boy Carpenter", unit: "Day"},
          {name: "Carpenter", unit: "Day"},
          {name: "Head Sculptor", unit: "Day"},
          {name: "Sculptor", unit: "Day"},
          {name: "Plumber", unit: "Day"},
          {name: "Mason", unit: "Day"},
          {name: "Visual Artist", unit: "Day"},
          {name: "Gaffer", unit: "Day"},
          {name: "Best Boy Electrician", unit: "Day"},
          {name: "Electrician", unit: "Day"},
          {name: "Head Set Metal Worker", unit: "Day"},
          {name: "Set Metal Worker", unit: "Day"},
          {name: "Set Carpenter", unit: "Day"},
          {name: "Head Plasterer", unit: "Day"},
          {name: "Best Boy Plasterer", unit: "Day"},
          {name: "Set Plasterer", unit: "Day"},
          {name: "Set Carpenter Woodcarver", unit: "Day"},
          {name: "Model Maker", unit: "Day"},
          {name: "Agent Commission (Serv.)", unit: "Fee"},
        ]
      },
      {
        name: "7.13. Others",
        items: [
          {name: "Drivers Overtime Hours", unit: "Fee"},
          {name: "Overtime Hours", unit: "Fee"},
          {name: "Offset Meal Time Penalties (Covid)", unit: "Fee"},
          {name: "Social Contributions Dir. (Serv.)", unit: "Fee"},
          {name: "Social Contributions Crew (Serv.)", unit: "Fee"},
        ]
      },
    ]
  },
  {
    id: "B",
    name: "B. EQUIPMENT",
    subs: [
      {
        name: "8.1. Equipment/Camera & Accessories",
        items: [
          {name: "Phantom", unit: "Day"},
          {name: "Red", unit: "Day"},
          {name: "Alexa", unit: "Day"},
          {name: "Camera 35mm Sound", unit: "Day"},
          {name: "Camera 35mm Mute", unit: "Day"},
          {name: "Camera 16mm", unit: "Day"},
          {name: "2nd Camera Body", unit: "Day"},
          {name: "Digital Camera HD", unit: "Day"},
          {name: "Classic Lenses Set", unit: "Day"},
          {name: "Extra Lenses", unit: "Day"},
          {name: "Zoom", unit: "Day"},
          {name: "Anamorphic Lenses Set", unit: "Day"},
          {name: "Macro Lenses Set", unit: "Day"},
          {name: "Camera Accessories", unit: "Day"},
          {name: "Others Accessories", unit: "Day"},
          {name: "Video & Tapes", unit: "Day"},
          {name: "Remote & Wi-Fi Connection", unit: "Day"},
          {name: "HF System", unit: "Day"},
          {name: "Duratrans/Colorama (backgrounds)", unit: "Day"},
          {name: "Filters", unit: "Day"},
          {name: "Pods & Heads", unit: "Day"},
          {name: "Frazier", unit: "Day"},
          {name: "Print Video & Tapes", unit: "Day"},
          {name: "View Finder", unit: "Day"},
          {name: "Video Playback System", unit: "Day"},
          {name: "Cinetools", unit: "Day"},
          {name: "DIT Equipment Kit", unit: "Day"},
          {name: "Digital Capturing", unit: "Day"},
          {name: "Extra Monitors & Cables", unit: "Day"},
          {name: "Rental Insurance (Serv.)", unit: "Fee"},
          {name: "Rental Insurance", unit: "Fee"},
        ]
      },
      {
        name: "8.2. Grip Equipment",
        items: [
          {name: "Dolly/Panther", unit: "Day"},
          {name: "Standard Grip Equipment", unit: "Day"},
          {name: "Crane", unit: "Day"},
          {name: "Louma/Techno", unit: "Day"},
          {name: "Hot Head", unit: "Day"},
          {name: "Steadicam", unit: "Day"},
          {name: "Cherry Picker", unit: "Day"},
          {name: "Motion Control (+ operator)", unit: "Day"},
          {name: "Wescam/Stab C", unit: "Day"},
          {name: "Russian Arm Excl. Crew", unit: "Day"},
          {name: "Drone (+ 2 technicians)", unit: "Day"},
          {name: "Towers, Scaffolding, Cherry Picker", unit: "Day"},
          {name: "Spinner", unit: "Day"},
          {name: "Accessories", unit: "Day"},
          {name: "Grip's Equipment", unit: "Day"},
          {name: "Tracking Car", unit: "Day"},
          {name: "Transport Tracking Car", unit: "Hour"},
          {name: "Drone", unit: "Unit"},
          {name: "Helicopter", unit: "Fee"},
          {name: "Helicopter Permits", unit: "Fee"},
          {name: "Transport Wescam/Stab C", unit: "Fee"},
          {name: "HF Relay", unit: "Day"},
          {name: "Helicopter Fuel", unit: "Fee"},
          {name: "Gas, Mileage & Tolls", unit: "Fee"},
          {name: "Kerosene Truck", unit: "Fee"},
          {name: "Rental Insurance (Serv.)", unit: "Fee"},
          {name: "Rental Insurance", unit: "Fee"},
        ]
      },
      {
        name: "8.3. Sound Rental",
        items: [
          {name: "Sound Equipment", unit: "Day"},
          {name: "Walkie-talkie (pair)", unit: "Day"},
          {name: "Playback System", unit: "Day"},
          {name: "Electronic Clap", unit: "Day"},
          {name: "Mobile Phones", unit: "Day"},
          {name: "Sound Accessories", unit: "Day"},
          {name: "Walkie-talkie Bags", unit: "Day"},
          {name: "Rental Insurance (Serv.)", unit: "Fee"},
          {name: "Rental Insurance", unit: "Fee"},
        ]
      },
      {
        name: "8.4. Lighting Rental",
        items: [
          {name: "Generator Rental", unit: "Day"},
          {name: "Generator Gasoline", unit: "Day"},
          {name: "Mobile Generator", unit: "Day"},
          {name: "Lighting Rental/Outdoors", unit: "Day"},
          {name: "Lighting Rental/Indoors", unit: "Day"},
          {name: "Lamps", unit: "Day"},
          {name: "HMI Consumption", unit: "Day"},
          {name: "Gaffer's Equipment", unit: "Day"},
          {name: "Towers & Light Bridges", unit: "Day"},
          {name: "Supplies (gels…)", unit: "Day"},
          {name: "Gasoline, Mileage & Toll", unit: "Day"},
          {name: "Delivery", unit: "Day"},
          {name: "Lighting Miscellaneous", unit: "Day"},
          {name: "Rental Insurance (Serv.)", unit: "Fee"},
          {name: "Rental Insurance", unit: "Fee"},
        ]
      },
      {
        name: "8.5. Technical Vehicles",
        items: [
          {name: "Camera Truck (+ mileage)", unit: "Day"},
          {name: "Lighting Truck 1 (+ mileage)", unit: "Day"},
          {name: "Lighting Truck 2 (+ mileage)", unit: "Day"},
          {name: "Lighting Truck 3 (+ mileage)", unit: "Day"},
          {name: "Grip Truck (+ mileage)", unit: "Day"},
          {name: "Crane Truck 1 (+ mileage)", unit: "Day"},
          {name: "Remote Head Car (+ mileage)", unit: "Day"},
          {name: "DIT Car (+ mileage)", unit: "Day"},
          {name: "Sound Car (+ mileage)", unit: "Day"},
          {name: "Art Dept. Truck", unit: "Day"},
          {name: "Props SFX Truck", unit: "Day"},
          {name: "Props Car", unit: "Day"},
          {name: "Wardrobe Car", unit: "Day"},
          {name: "Stylist Car", unit: "Day"},
          {name: "Additional Car", unit: "Day"},
          {name: "Gasoline, Mileage & Toll Trucks", unit: "Fee"},
          {name: "Gasoline, Mileage & Toll Cars", unit: "Fee"},
          {name: "Fuel/Toll/Km Add. Car", unit: "Fee"},
          {name: "Rental Insurance (Serv.)", unit: "Fee"},
          {name: "Rental Insurance", unit: "Fee"},
        ]
      },
    ]
  },
  {
    id: "B",
    name: "B. ART DEPARTMENT & BEAUTY",
    subs: [
      {
        name: "9.1. Art department (purchase & rentals)",
        items: [
          {name: "Decoration Costs", unit: "Unit"},
          {name: "Props Purchase & Rent", unit: "Unit"},
          {name: "Props Creation", unit: "Unit"},
          {name: "Plants", unit: "Unit"},
          {name: "Set constr. Costs", unit: "Fee"},
          {name: "Raw Material, Wood, Paint…", unit: "Unit"},
          {name: "Paint, Canvas", unit: "Fee"},
          {name: "Wooden Floor", unit: "Fee"},
          {name: "Hardware", unit: "Fee"},
          {name: "Other Raw Material", unit: "Fee"},
          {name: "Tools Fee/Hardware", unit: "Fee"},
          {name: "Furniture Purchase & Rent", unit: "Fee"},
          {name: "Paint/Floor", unit: "Fee"},
          {name: "Picture Vehicle", unit: "Unit"},
          {name: "Smoke Machine", unit: "Unit"},
          {name: "Smoke Bomb", unit: "Unit"},
          {name: "Wind Machine", unit: "Unit"},
          {name: "Explosives", unit: "Fee"},
          {name: "Rain Equipment", unit: "Unit"},
          {name: "Water Truck", unit: "Fee"},
          {name: "SFX Purchases", unit: "Fee"},
          {name: "Mock-ups (products)", unit: "Fee"},
          {name: "Set Equipment Disinfection", unit: "Fee"},
        ]
      },
      {
        name: "9.2. Stylism",
        items: [
          {name: "Costume Design", unit: "Unit"},
          {name: "Purchase & Rent Lead Roles", unit: "Fee"},
          {name: "Purchase & Rent Secondary Roles", unit: "Fee"},
          {name: "Purchase & Rent Extras", unit: "Fee"},
          {name: "Accessories", unit: "Fee"},
          {name: "Styling Expenses (rails, hangers, robes, steamer...)", unit: "Fee"},
          {name: "Wardrobe Expenses (retouching…)", unit: "Fee"},
          {name: "Safe", unit: "Fee"},
          {name: "Styling Room Rental", unit: "Fee"},
          {name: "Cleaning", unit: "Fee"},
          {name: "Stylism Equipment Disinfection", unit: "Fee"},
          {name: "Kit Rental Home Economist", unit: "Fee"},
        ]
      },
      {
        name: "9.3. Makeup & Hair",
        items: [
          {name: "Makeup & Wigs", unit: "Fee"},
          {name: "SFX Makeup", unit: "Fee"},
          {name: "Makeup Disinfection Kit", unit: "Fee"},
          {name: "Styling Room Rental", unit: "Day"},
          {name: "Cleaning", unit: "Fee"},
          {name: "Fridge", unit: "Fee"},
        ]
      },
    ]
  },
  {
    id: "B",
    name: "B. STUDIO",
    subs: [
      {
        name: "10.1. Studio Rent",
        items: [
          {name: "Studio (build)", unit: "Day"},
          {name: "Studio (pre-light)", unit: "Day"},
          {name: "Studio (shoot)", unit: "Day"},
          {name: "Studio (wrap)", unit: "Day"},
          {name: "Studio (overtime)", unit: "Day"},
          {name: "Carpentry Department", unit: "Day"},
          {name: "Dressing Room", unit: "Day"},
          {name: "Production Rooms", unit: "Day"},
        ]
      },
      {
        name: "10.2. Material Costs",
        items: [
          {name: "Raw Material, Wood, Paint…", unit: "Fee"},
          {name: "Paint, Canvas", unit: "Fee"},
          {name: "Wooden Floor", unit: "Fee"},
          {name: "Hardware", unit: "Fee"},
          {name: "Other Raw Material", unit: "Fee"},
          {name: "Tools Fee/Hardware", unit: "Day"},
          {name: "Furniture Purchase & Rent", unit: "Unit"},
          {name: "Paint/Floor", unit: "Fee"},
        ]
      },
      {
        name: "10.3. Miscellaneous",
        items: [
          {name: "Power Supply (build, pre-light, wrap)", unit: "Day"},
          {name: "Power Supply (shoot)", unit: "Day"},
          {name: "Heating & Air Con", unit: "Day"},
          {name: "Cleaning", unit: "Fee"},
          {name: "Electrical Hoists/Light Bridges", unit: "Day"},
          {name: "Skip Bins", unit: "Day"},
          {name: "Miscellaneous Studio Charges", unit: "Fee"},
          {name: "Telephone", unit: "Fee"},
        ]
      },
    ]
  },
  {
    id: "B",
    name: "B. LOCATIONS",
    subs: [
      {
        name: "11.1. Natural Locations Hire",
        items: [
          {name: "Location 1 Fee (shoot)", unit: "Day"},
          {name: "Location 1 Fee (setup/wrap)", unit: "Day"},
          {name: "Location 2 Fee (shoot)", unit: "Day"},
          {name: "Location 2 Fee (setup/wrap)", unit: "Day"},
          {name: "Shoot Permits", unit: "Fee"},
          {name: "Green Room", unit: "Fee"},
          {name: "Basecamp", unit: "Day"},
          {name: "Owner Accommodation", unit: "Day"},
          {name: "Parking Permits", unit: "Unit"},
          {name: "Disinfection of Private Places", unit: "Fee"},
        ]
      },
      {
        name: "11.2. Miscellaneous",
        items: [
          {name: "Unit & Basecamp Setup", unit: "Fee"},
          {name: "Location Expenses (tables, chairs, heaters…)", unit: "Day"},
          {name: "Street/Car Park Blocking", unit: "Fee"},
          {name: "Set Dressing Supplies", unit: "Unit"},
          {name: "Electric Extension", unit: "Unit"},
          {name: "Power Unit", unit: "Day"},
          {name: "Honey Wagon", unit: "Fee"},
          {name: "Location Security", unit: "Fee"},
          {name: "Police & Firemen", unit: "Fee"},
          {name: "Damage Repairs", unit: "Fee"},
          {name: "Waste Container", unit: "Fee"},
          {name: "Cleaning", unit: "Fee"},
          {name: "Weather Forecast", unit: "Unit"},
          {name: "Parking", unit: "Fee"},
          {name: "Taxis", unit: "Fee"},
          {name: "Cabs Airport", unit: "Fee"},
          {name: "Extras Transportation", unit: "Fee"},
          {name: "Car & Parking Allowance Crew", unit: "Fee"},
          {name: "Miscellaneous", unit: "Fee"},
        ]
      },
    ]
  },
  {
    id: "B",
    name: "B. PRODUCTION PHOTO",
    subs: [
      {
        name: "12.1. Crew",
        items: [
          {name: "Photographer's Fee", unit: "Day"},
          {name: "Photographer's Buyout", unit: "Day"},
          {name: "Producer", unit: "Day"},
          {name: "Production Ass.", unit: "Day"},
          {name: "1st Photographer Ass.", unit: "Day"},
          {name: "2nd Photographer Ass.", unit: "Day"},
          {name: "3rd Photographer Ass.", unit: "Day"},
          {name: "Digitech & Equipment Studio", unit: "Day"},
          {name: "Stylist", unit: "Day"},
          {name: "Ass. Stylist", unit: "Day"},
          {name: "Set Designer & Props Stylist", unit: "Day"},
          {name: "Flower Stylist", unit: "Day"},
          {name: "Props Stylist", unit: "Day"},
          {name: "Hair Stylist", unit: "Day"},
          {name: "Ass. Hair Stylist", unit: "Day"},
          {name: "Makeup Artist", unit: "Day"},
          {name: "Ass. Makeup Artist", unit: "Day"},
          {name: "Manicurist", unit: "Day"},
          {name: "Agent Commission (Serv.)", unit: "Fee"},
          {name: "Agent Commission", unit: "Fee"},
          {name: "Social Contributions (Serv.)", unit: "Fee"},
          {name: "Social Contributions", unit: "Fee"},
        ]
      },
      {
        name: "12.2. Models",
        items: [
          {name: "Casting Director", unit: "Day"},
          {name: "Model", unit: "Day"},
          {name: "Agent Commission (Serv.)", unit: "Fee"},
          {name: "Agent Commission", unit: "Fee"},
          {name: "Social Contributions (Serv.)", unit: "Fee"},
          {name: "Social Contributions", unit: "Fee"},
        ]
      },
      {
        name: "12.3. Equipment & Accessories",
        items: [
          {name: "Light Equipment", unit: "Day"},
          {name: "Small Photo Equipment", unit: "Day"},
          {name: "Photo Retouching (ex. Qtake)", unit: "Day"},
          {name: "DIT Equipment Kit", unit: "Day"},
          {name: "Digital", unit: "Fee"},
        ]
      },
      {
        name: "12.4. Locations, Art, Stylism, Hair & Makeup",
        items: [
          {name: "Studio", unit: "Day"},
          {name: "Location", unit: "Day"},
          {name: "Set Design Material", unit: "Day"},
          {name: "Props Stylist Expenses Provision", unit: "Fee"},
          {name: "Set Designer Expenses Provision", unit: "Fee"},
          {name: "Flower Stylist Expenses Provision", unit: "Fee"},
        ]
      },
      {
        name: "12.5. Miscellaneous",
        items: [
          {name: "Location Scouting", unit: "Day"},
          {name: "Casting Expenses", unit: "Day"},
          {name: "Catering", unit: "Day"},
          {name: "Photo Retouching", unit: "Fee"},
          {name: "Approvals", unit: "Fee"},
          {name: "Courier", unit: "Day"},
        ]
      },
      {
        name: "12.6. Rights",
        items: [
          {name: "Talents Usage Fee", unit: "Fee"},
          {name: "Models Usage Fee", unit: "Fee"},
          {name: "Child Usage Fee", unit: "Fee"},
          {name: "Agent Commission (Serv.)", unit: "Fee"},
          {name: "Agent Commission", unit: "Fee"},
          {name: "Social Contributions (Serv.)", unit: "Fee"},
          {name: "Social Contributions", unit: "Fee"},
        ]
      },
    ]
  },
  {
    id: "B",
    name: "B. HARD DISKS, STOCK, LABORATORY",
    subs: [
      {
        name: "B. HARD DISKS, STOCK, LABORATORY",
        items: [
          {name: "Hard Drives Master", unit: "Unit"},
          {name: "Hard Drives", unit: "Unit"},
          {name: "16/35mm Colour Raw Stock (122 M)", unit: "Box"},
          {name: "16/35mm B&W Raw Stock (122 M)", unit: "Box"},
          {name: "Dev. 16/35mm Colour & Grading Prep", unit: "Fee"},
          {name: "Dev. 16/35mm B&W", unit: "Fee"},
          {name: "Lab Opening Weekend", unit: "Fee"},
          {name: "Shots Selection (def. Grading)", unit: "Frame"},
          {name: "Magnetic 6,25mm", unit: "Box"},
          {name: "Dat", unit: "Unit"},
          {name: "Graded Printing 16/35mm", unit: "Fee"},
          {name: "Printing B&W 16/35mm", unit: "Fee"},
          {name: "Rushes Transport/Hard Drives", unit: "Fee"},
          {name: "Sync./Screen Dailies", unit: "Fee"},
          {name: "Rushes Screening", unit: "Fee"},
          {name: "Moviola Rental", unit: "Day"},
          {name: "Rushes Cleaning", unit: "Fee"},
          {name: "Packing", unit: "Fee"},
          {name: "Transportation", unit: "Fee"},
          {name: "Transfer to 16/35mm", unit: "Fee"},
          {name: "Magnetic 16/35mm", unit: "Box"},
          {name: "Developing Negative", unit: "Fee"},
          {name: "Dev. 1st Graded Positive", unit: "Fee"},
          {name: "Developing Sound Negative", unit: "Fee"},
        ]
      },
    ]
  },
  {
    id: "B",
    name: "B. LOCATION EXPENSES, MISCELLANEOUS",
    subs: [
      {
        name: "13.1. Transports",
        items: [
          {name: "Director's Car", unit: "Day"},
          {name: "Car-lodges", unit: "Day"},
          {name: "Production Vans", unit: "Day"},
          {name: "Production Cars", unit: "Day"},
          {name: "Disinfected Shooting Crew Car/Van", unit: "Day"},
          {name: "Talents Vans", unit: "Day"},
          {name: "Agency & Client Vans", unit: "Day"},
          {name: "Unit Truck", unit: "Day"},
          {name: "Catering Truck", unit: "Day"},
          {name: "Airports & Train Stations Transfers", unit: "Unit"},
          {name: "VIP Transfers", unit: "Unit"},
          {name: "Taxis/Car Service", unit: "Unit"},
          {name: "Extras Transportation", unit: "Unit"},
          {name: "Car & Parking Allowance Crew", unit: "Fee"},
          {name: "Additional Car Gasoline", unit: "Fee"},
          {name: "Gasoline, Mileage, Tolls, Parking Trucks", unit: "Fee"},
          {name: "Gasoline, Mileage, Tolls, Parking Cars", unit: "Fee"},
          {name: "Rental Insurance (Serv.)", unit: "Fee"},
          {name: "Rental Insurance", unit: "Fee"},
        ]
      },
      {
        name: "13.2. Other costs",
        items: [
          {name: "Communications", unit: "Fee"},
          {name: "Messenger/Deliveries", unit: "Fee"},
          {name: "Bank Fees", unit: "Fee"},
          {name: "Transaction Fee (financial portage)", unit: "Fee"},
          {name: "Accounting Flat Fee", unit: "Fee"},
          {name: "Budgeting Software", unit: "Fee"},
          {name: "Dematerialisation & Carbon Print Software", unit: "Fee"},
          {name: "Contingency", unit: "Fee"},
          {name: "ATA Carnet, Air Shipping, Custom Clearance", unit: "Fee"},
          {name: "Rushes Transportation/Hard Drives", unit: "Fee"},
          {name: "Excess Luggage", unit: "Fee"},
          {name: "Local Tax", unit: "Fee"},
          {name: "Film Commission", unit: "Fee"},
          {name: "Unit Kit (tent, rent…)", unit: "Unit"},
          {name: "Production Kit", unit: "Unit"},
          {name: "Catering Tent", unit: "Unit"},
          {name: "Protection Kit (Covid)", unit: "Unit"},
          {name: "Covid Tests (PCR)", unit: "Unit"},
          {name: "Covid Referrer Kit", unit: "Unit"},
          {name: "Soap Dispenser/Hand Dryer (Covid)", unit: "Unit"},
          {name: "Hydro-alco. Gel, Wipes, Slippers (Covid)", unit: "Unit"},
          {name: "Masks, Gloves, Visors (Covid)", unit: "Unit"},
        ]
      },
      {
        name: "13.3. Production Service Expenses and Fee",
        items: [
          {name: "Production Expenses", unit: "Fee"},
          {name: "Communications", unit: "Fee"},
          {name: "Office Expenses", unit: "Fee"},
          {name: "Production Fee", unit: "Fee"},
          {name: "Service production Markup", unit: "Fee"},
        ]
      },
    ]
  },
  {
    id: "C",
    name: "C. POST-PRODUCTION IMAGE",
    subs: [
      {
        name: "14. Video",
        items: [
        ]
      },
      {
        name: "14.1. Supervision",
        items: [
          {name: "Lead Post-Producer", unit: "Day"},
          {name: "Post Production Manager PP1", unit: "Day"},
          {name: "Post Production Manager PP2", unit: "Day"},
          {name: "VFX Producer", unit: "Day"},
          {name: "3D Production Coordinator", unit: "Day"},
          {name: "Coordinator", unit: "Week"},
          {name: "SFX Supervisor on Shooting", unit: "Day"},
          {name: "Week-end Flat Rate Saturday (/pers)", unit: "Day"},
          {name: "Week-end Flat Rate Sunday (/pers)", unit: "Day"},
        ]
      },
      {
        name: "14.2. Editing",
        items: [
          {name: "Chef Editor", unit: "Day"},
          {name: "Editor", unit: "Day"},
          {name: "Editor Ass.", unit: "Day"},
          {name: "Rushes Conversion", unit: "Hour"},
          {name: "HD File Transfer", unit: "Hour"},
          {name: "Rushes Synchro Video (15 takes/hour)", unit: "Fee"},
          {name: "AVID Editing Room", unit: "Day"},
          {name: "Premiere Editing Room", unit: "Day"},
          {name: "Editor Motion (+ station)", unit: "Day"},
          {name: "Compression H264 (fee)", unit: "Fee"},
          {name: "AAF & OMF Export", unit: "Fee"},
          {name: "Editing Back-up/Restoring/Saving", unit: "Fee"},
          {name: "FTP Compressions", unit: "Fee"},
          {name: "Hard Disks", unit: "Unit"},
        ]
      },
      {
        name: "14.3. Stock-shots & Rights",
        items: [
          {name: "Stock-shot Researcher", unit: "Fee"},
          {name: "Stock-shot (all rights)", unit: "Fee"},
          {name: "Stock-shot (all rights 1 year World) TV+Digital", unit: "Fee"},
          {name: "Stock-shot (all rights 1 year Europe) TV+Digital", unit: "Fee"},
          {name: "Stock-shot (all rights 1 year France) TV+Digital", unit: "Fee"},
          {name: "Stock-shot (all rights 1 year World) Digital Only", unit: "Fee"},
          {name: "Stock-shot (all rights 1 year Europe) Digital Only", unit: "Fee"},
          {name: "Stock-shot (all rights 1 year France) Digital Only", unit: "Fee"},
        ]
      },
      {
        name: "14.4. Grading",
        items: [
          {name: "Colourist", unit: "Hour"},
          {name: "Colourist Ass.", unit: "Hour"},
          {name: "Dailies Transfer on Resolve", unit: "Hour"},
          {name: "Conformation for Colouring", unit: "Hour"},
          {name: "Conformation HD", unit: "Hour"},
          {name: "Grading Room HD/2K", unit: "Hour"},
          {name: "Grading Station (+ colourist in house)", unit: "Day"},
          {name: "Base Light HD", unit: "Fee"},
          {name: "Clearview Link", unit: "Fee"},
          {name: "DPX Export", unit: "Fee"},
          {name: "Grading Back-up/Restoring/Archiving", unit: "Fee"},
          {name: "HD Data Transfer on Hard Drive", unit: "Fee"},
          {name: "Digital Supplies", unit: "Fee"},
        ]
      },
      {
        name: "14.5. Laboratory",
        items: [
          {name: "Project Setup", unit: "Fee"},
          {name: "Import Rushes", unit: "Unit"},
          {name: "Telecinema Right MPC", unit: "Hour"},
          {name: "Transcoding Raw DPX", unit: "Fee"},
          {name: "Import Data", unit: "Unit"},
          {name: "Scan Setup", unit: "Unit"},
          {name: "Spirit 2K Scan Negative", unit: "Meter"},
          {name: "Baselight Confo", unit: "Unit"},
          {name: "Baselight Grading", unit: "Hour"},
          {name: "Baselight Assistant", unit: "Hour"},
          {name: "Hard Disks", unit: "Unit"},
          {name: "Data transfer", unit: "Fee"},
          {name: "FTP Transfer", unit: "Fee"},
          {name: "LTO for Archive", unit: "Fee"},
          {name: "Back-up", unit: "Fee"},
        ]
      },
      {
        name: "14.6. Animation & Finalization",
        items: [
          {name: "Flame Graphic Artist", unit: "Hour"},
          {name: "Flame Ass.", unit: "Day"},
          {name: "Flame Assist HD", unit: "Hour"},
          {name: "After Effect Graphic Artist", unit: "Day"},
          {name: "Motion Designer", unit: "Day"},
          {name: "Graphic Artist Ass.", unit: "Day"},
          {name: "DPX/QTNC/PRORES Import", unit: "Fee"},
          {name: "Flame Room", unit: "Hour"},
          {name: "Flare Station", unit: "Hour"},
          {name: "Nuke Station", unit: "Day"},
          {name: "Matte Painting", unit: "Unit"},
          {name: "After Effects Station", unit: "Day"},
          {name: "After Effects (+ graphic designer)", unit: "Day"},
          {name: "Subtitling/Minute/Language", unit: "Fee"},
          {name: "Compression H264", unit: "Fee"},
          {name: "DCP File Creation (per spot flat + scope)", unit: "Fee"},
          {name: "DCP Projection", unit: "Hour"},
          {name: "Mastering", unit: "Hour"},
          {name: "Finalisation Back-up/Restoring/Archiving (5 years)", unit: "Fee"},
          {name: "Inut/Output", unit: "Fee"},
        ]
      },
      {
        name: "15. CGI",
        items: [
        ]
      },
      {
        name: "15.1. Supervision",
        items: [
          {name: "Director", unit: "Day"},
          {name: "Director's Agent", unit: "Day"},
          {name: "VFX Producer", unit: "Day"},
          {name: "3D Production Coordinator", unit: "Day"},
          {name: "Coordinator", unit: "Week"},
          {name: "SFX Supervisor on Shooting", unit: "Day"},
          {name: "Supervisor Studio", unit: "Day"},
          {name: "Week-end Flat Rate Saturday (/pers)", unit: "Day"},
          {name: "Week-end Flat Rate Sunday (/pers)", unit: "Day"},
          {name: "Business Affairs", unit: "Day"},
          {name: "R&D", unit: "Day"},
          {name: "Line Test", unit: "Day"},
          {name: "Animatic 3D", unit: "Unit"},
        ]
      },
      {
        name: "15.2. Shot 1",
        items: [
          {name: "Line Test", unit: "Day"},
          {name: "Cleaning (+ graphic designer)", unit: "Day"},
          {name: "Cleaning (+ graphic designer) - Ext Vehicle", unit: "Fee"},
          {name: "Cleaning (+ graphic designer) - Int Vehicle", unit: "Fee"},
          {name: "3D Modeling Characters (+ graphic designer)", unit: "Fee"},
          {name: "3D Modeling Props (+ graphic designer)", unit: "Fee"},
          {name: "3D Modeling Set (+ graphic designer)", unit: "Day"},
          {name: "Setup/Rigging (+ graphic designer)", unit: "Fee"},
          {name: "Rigging Char & Vehicles (+ graphic designer)", unit: "Fee"},
          {name: "Animation (+ graphic designer)", unit: "Fee"},
          {name: "Texture/Shading (+ graphic designer)", unit: "Fee"},
          {name: "Lighting/Rendering (+ graphic designer)", unit: "Fee"},
          {name: "Rendering (+ graphic designer)", unit: "Fee"},
          {name: "Rotoscopy (+ graphic designer)", unit: "Fee"},
          {name: "Tracking (+ graphic designer)", unit: "Fee"},
          {name: "Camera Mapping (+ graphic designer)", unit: "Day"},
          {name: "Particles/Climatic FX (+ graphic designer)", unit: "Day"},
          {name: "Fluids (+ graphic designer)", unit: "Day"},
          {name: "Fire & Smoke (+ graphic designer)", unit: "Day"},
          {name: "Fur (+ graphic designer)", unit: "Day"},
          {name: "Cloth (+ graphic designer)", unit: "Day"},
          {name: "Compositing on Nuke (+ graphic designer)", unit: "Fee"},
          {name: "Purchase of GCI Model", unit: "Fee"},
          {name: "Compliance", unit: "Fee"},
          {name: "Photo Editing (Photoshop)", unit: "Fee"},
          {name: "Graphic Design Creation", unit: "Fee"},
          {name: "Matte Painting 3D (+ graphic designer)", unit: "Day"},
        ]
      },
      {
        name: "15.3. Shot 2",
        items: [
          {name: "Line Test", unit: "Day"},
          {name: "Cleaning (+ graphic designer)", unit: "Day"},
          {name: "Cleaning (+ graphic designer) - Ext Vehicle", unit: "Fee"},
          {name: "Cleaning (+ graphic designer) - Int Vehicle", unit: "Fee"},
          {name: "3D Modeling Characters (+ graphic designer)", unit: "Fee"},
          {name: "3D Modeling Props (+ graphic designer)", unit: "Fee"},
          {name: "3D Modeling Set (+ graphic designer)", unit: "Day"},
          {name: "Setup/Rigging (+ graphic designer)", unit: "Fee"},
          {name: "Rigging Char & Vehicles (+ graphic designer)", unit: "Fee"},
          {name: "Animation (+ graphic designer)", unit: "Fee"},
          {name: "Texture/Shading (+ graphic designer)", unit: "Fee"},
          {name: "Lighting/Rendering (+ graphic designer)", unit: "Fee"},
          {name: "Rendering (+ graphic designer)", unit: "Fee"},
          {name: "Rotoscopy (+ graphic designer)", unit: "Fee"},
          {name: "Tracking (+ graphic designer)", unit: "Fee"},
          {name: "Camera Mapping (+ graphic designer)", unit: "Day"},
          {name: "Particles/Climatic FX (+ graphic designer)", unit: "Day"},
          {name: "Fluids (+ graphic designer)", unit: "Day"},
          {name: "Fire & Smoke (+ graphic designer)", unit: "Day"},
          {name: "Fur (+ graphic designer)", unit: "Day"},
          {name: "Cloth (+ graphic designer)", unit: "Day"},
          {name: "Compositing on Nuke (+ graphic designer)", unit: "Fee"},
          {name: "Purchase of GCI Model", unit: "Fee"},
          {name: "Compliance", unit: "Fee"},
          {name: "Photo Editing (Photoshop)", unit: "Fee"},
          {name: "Graphic Design Creation", unit: "Fee"},
          {name: "Matte Painting 3D (+ graphic designer)", unit: "Day"},
        ]
      },
      {
        name: "15.4. Miscellaneous",
        items: [
          {name: "Render Farm", unit: "Fee"},
          {name: "Compression H264", unit: "Fee"},
          {name: "Back-up/Restore/Archive 3D", unit: "Fee"},
          {name: "Expenses", unit: "Fee"},
          {name: "Courrier", unit: "Fee"},
          {name: "Insurances", unit: "Fee"},
        ]
      },
      {
        name: "16. Creative Retouching",
        items: [
        ]
      },
      {
        name: "16.1. Supervision",
        items: [
          {name: "Project Manager", unit: "Day"},
        ]
      },
      {
        name: "16.2. Creative Retouching",
        items: [
          {name: "Retoucher on Set", unit: "Day"},
          {name: "Retouching", unit: "Fee"},
          {name: "Colour Retouching", unit: "Fee"},
        ]
      },
      {
        name: "16.3. Chromatic Alignment",
        items: [
          {name: "Chromatic Alignment", unit: "Fee"},
        ]
      },
      {
        name: "16.4. Visual check",
        items: [
          {name: "Visual Check", unit: "Fee"},
        ]
      },
      {
        name: "16.5. Merchandising",
        items: [
          {name: "Merchandising", unit: "Fee"},
        ]
      },
      {
        name: "16.6. Proof",
        items: [
          {name: "Proof", unit: "Fee"},
        ]
      },
      {
        name: "16.7. Image Format",
        items: [
          {name: "PDF", unit: "Fee"},
          {name: "JPEG", unit: "Fee"},
          {name: "TIFF", unit: "Fee"},
          {name: "Link/Native", unit: "Fee"},
        ]
      },
      {
        name: "16.8. Layout",
        items: [
          {name: "Epson A4", unit: "Fee"},
          {name: "Epson A3", unit: "Fee"},
          {name: "Epson A2", unit: "Fee"},
          {name: "Epson A1", unit: "Fee"},
          {name: "Epson A0", unit: "Fee"},
        ]
      },
      {
        name: "17. Miscellaneous",
        items: [
          {name: "Phone, Taxi, Restaurants (per film)", unit: "Unit"},
          {name: "Normal Courier", unit: "Unit"},
          {name: "Exclusive Courier (< 1h)", unit: "Unit"},
          {name: "DHL", unit: "Fee"},
          {name: "Insurances", unit: "Fee"},
          {name: "Agent Commission (Serv.)", unit: "Fee"},
          {name: "Agent Commission", unit: "Fee"},
          {name: "Social Contributions (Serv.)", unit: "Fee"},
          {name: "Social Contributions", unit: "Fee"},
        ]
      },
    ]
  },
  {
    id: "D",
    name: "D. POST-PRODUCTION SOUND & MUSIC",
    subs: [
      {
        name: "18. Post-production Sound (SD / VO / Mix)",
        items: [
        ]
      },
      {
        name: "Wages",
        items: [
          {name: "VO Talent Fee", unit: "Fee"},
          {name: "Sound Designer", unit: "Day"},
          {name: "Sound Producer/Director", unit: "Hour"},
          {name: "Sound Engineer", unit: "Hour"},
          {name: "Sound Ass.", unit: "Hour"},
          {name: "Production Supervision", unit: "Fee"},
          {name: "Copywriter", unit: "Fee"},
          {name: "Sound Effects Engineer", unit: "Day"},
          {name: "Journalist", unit: "Day"},
          {name: "Journalist-reporter", unit: "Day"},
          {name: "Miscellaneous", unit: "Fee"},
        ]
      },
      {
        name: "Technical & Conception",
        items: [
          {name: "Sound Production", unit: "Fee"},
          {name: "Production Supervision", unit: "Fee"},
          {name: "Production Coordination", unit: "Fee"},
          {name: "Sound Studio Rental", unit: "Hour"},
          {name: "Sound Producer/Director", unit: "Hour"},
          {name: "Sound Engineer", unit: "Hour"},
          {name: "ISDN/SCE link", unit: "Fee"},
          {name: "Auditorium 5.1 (+ sound engineer)", unit: "Fee"},
          {name: "Dolby Licence", unit: "Fee"},
          {name: "Sound Transfer Equipment", unit: "Unit"},
          {name: "Supply/Back-up/Archiving", unit: "Day"},
          {name: "Audio Transfer", unit: "Fee"},
          {name: "VO Talent's Fee", unit: "Fee"},
          {name: "VO Talent's Agent Fee", unit: "Fee"},
          {name: "Casting (on demo) for 1 Role", unit: "Fee"},
          {name: "Supplies", unit: "Day"},
          {name: "Musical Search", unit: "Fee"},
          {name: "Effects Search", unit: "Unit"},
          {name: "Conception", unit: "Fee"},
          {name: "Journalist", unit: "Fee"},
          {name: "Journalist-reporter", unit: "Fee"},
          {name: "Guidelines", unit: "Fee"},
          {name: "Copywriting", unit: "Fee"},
          {name: "Translation", unit: "Fee"},
          {name: "Radio Stations Delivery", unit: "Fee"},
          {name: "Sound Recording Equipment (outdoor)", unit: "Fee"},
          {name: "Miscellaneous", unit: "Fee"},
          {name: "Expenses (cabs/restaurant)", unit: "Fee"},
        ]
      },
      {
        name: "19. Post-Production Music",
        items: [
        ]
      },
      {
        name: "Wages",
        items: [
          {name: "Composer/Arranger", unit: "Fee"},
          {name: "Orchestrator", unit: "Fee"},
          {name: "Conductor", unit: "Fee"},
          {name: "Synth Programmer", unit: "Fee"},
          {name: "Musician", unit: "Fee"},
          {name: "Lead Singer", unit: "Fee"},
          {name: "Chorus Singer", unit: "Fee"},
          {name: "Copyist", unit: "Fee"},
          {name: "Tuner", unit: "Fee"},
          {name: "Music Contractor", unit: "Fee"},
          {name: "Orchestra", unit: "Fee"},
          {name: "Sound Designer", unit: "Fee"},
          {name: "Sound Producer/Director", unit: "Hour"},
          {name: "Sound Engineer", unit: "Hour"},
          {name: "Sound Editor's Ass.", unit: "Hour"},
          {name: "Music Supervision", unit: "Hour"},
          {name: "Miscellaneous", unit: "Fee"},
        ]
      },
      {
        name: "Technical & Conception",
        items: [
          {name: "Composer/Arranger Fee", unit: "Fee"},
          {name: "Home Studio", unit: "Day"},
          {name: "Production Supervision", unit: "Fee"},
          {name: "Sound Studio Rental", unit: "Hour"},
          {name: "Music Studio", unit: "Day"},
          {name: "Music Supervision", unit: "Fee"},
          {name: "Sound Production", unit: "Fee"},
          {name: "Audio Transfer", unit: "Fee"},
          {name: "Sound Transfer Equipment", unit: "Unit"},
          {name: "Sound Producer/Director", unit: "Hour"},
          {name: "Talent's Agent Fee", unit: "Fee"},
          {name: "Supply/Back-up/Archiving", unit: "Day"},
          {name: "Casting (on demo) for 1 Role", unit: "Fee"},
          {name: "Music Demo", unit: "Fee"},
          {name: "Musical Search", unit: "Fee"},
          {name: "Effects Search", unit: "Fee"},
          {name: "Instrument Transportation", unit: "Fee"},
          {name: "Miscellaneous", unit: "Fee"},
          {name: "Expenses (cabs/restaurant)", unit: "Fee"},
        ]
      },
      {
        name: "20. Music Rights",
        items: [
          {name: "Library Music UR", unit: "Fee"},
          {name: "Original Music UR", unit: "Fee"},
          {name: "Artist's UR", unit: "Fee"},
          {name: "VO Talent UR", unit: "Fee"},
          {name: "Business Affairs Handling Fee", unit: "Fee"},
          {name: "VO Talent 's Agent Fee", unit: "Fee"},
        ]
      },
      {
        name: "21. Digital Sound",
        items: [
          {name: "Recording Studio/pers & Backup", unit: "Hour"},
          {name: "Mix Studio/pers & Backup", unit: "Hour"},
          {name: "VO Talent's Recording Fee", unit: "Fee"},
          {name: "Sound Design", unit: "Fee"},
          {name: "VO Talent 's Agent Fee", unit: "Fee"},
          {name: "Casting (on demo) for 1 Role", unit: "Fee"},
          {name: "Musical Search", unit: "Fee"},
          {name: "VO Talent's UR", unit: "Fee"},
          {name: "Music UR", unit: "Fee"},
          {name: "Business Affairs Handling Fee", unit: "Fee"},
          {name: "Miscellaneous", unit: "Fee"},
          {name: "Agent Commission (Serv.)", unit: "Fee"},
          {name: "Agent Commission", unit: "Fee"},
          {name: "Social Contributions (Serv.)", unit: "Fee"},
          {name: "Social Contributions", unit: "Fee"},
        ]
      },
    ]
  },
  {
    id: "E",
    name: "E. PRODUCTION DIGITAL",
    subs: [
      {
        name: "22. Supervision",
        items: [
          {name: "Project Director", unit: "Day"},
          {name: "Lead Studio", unit: "Day"},
          {name: "Project Manager", unit: "Day"},
          {name: "Project Manager Ass.", unit: "Day"},
          {name: "DCO Manager", unit: "Day"},
        ]
      },
      {
        name: "23. Production Unit",
        items: [
          {name: "Copywriter", unit: "Day"},
          {name: "Editorial Strategist", unit: "Day"},
          {name: "SEO Strategist", unit: "Day"},
          {name: "Copywriter EN/FR", unit: "Day"},
          {name: "UX", unit: "Day"},
          {name: "Art Director", unit: "Day"},
          {name: "Motion Designer", unit: "Day"},
          {name: "Web Designer", unit: "Day"},
        ]
      },
      {
        name: "24. Assets Production",
        items: [
          {name: "Storyboarding", unit: "Fee"},
          {name: "Static Banner Master", unit: "Fee"},
          {name: "Static Banner Resizing", unit: "Fee"},
          {name: "Static Banner Copy Adaptation", unit: "Fee"},
          {name: "Animated Banner Master", unit: "Fee"},
          {name: "Animated Banner Resizing", unit: "Fee"},
          {name: "Animated Banner Copy Adaptation", unit: "Fee"},
          {name: "DCO Banner Master", unit: "Fee"},
          {name: "DCO Banner Resizing", unit: "Fee"},
          {name: "Update DCO Matrix File", unit: "Fee"},
          {name: "Rich Media Banner Master", unit: "Fee"},
          {name: "Rich Media Banner Resizing", unit: "Fee"},
          {name: "Rich Media Banner Copy Adaptation", unit: "Fee"},
          {name: "DOOH Master", unit: "Fee"},
          {name: "DOOH Resizing", unit: "Fee"},
          {name: "DOOH Copy Adaptation", unit: "Fee"},
          {name: "Gif Animated", unit: "Fee"},
          {name: "Backup Gif", unit: "Fee"},
          {name: "Banner Specification Updates (click tag)", unit: "Fee"},
          {name: "Video Encoding", unit: "Fee"},
          {name: "Traffic Management Publication Adserver", unit: "Fee"},
          {name: "Emailing - Design", unit: "Fee"},
          {name: "Emailing - HTML", unit: "Fee"},
          {name: "eADV - Design", unit: "Fee"},
          {name: "eADV - Technical Development", unit: "Fee"},
          {name: "Hosting - Setup", unit: "Fee"},
          {name: "Hosting - Monthly Cost", unit: "Fee"},
          {name: "DNS", unit: "Fee"},
          {name: "TMA - Technical Application Maintenance", unit: "Fee"},
          {name: "Other Costs", unit: "Fee"},
        ]
      },
      {
        name: "25. Development",
        items: [
          {name: "Technical Director", unit: "Fee"},
          {name: "Technical Architect", unit: "Fee"},
          {name: "Technical Project Manager", unit: "Fee"},
          {name: "Back-end Lead Developer", unit: "Fee"},
          {name: "Back-end Lead Developer (off-shore)", unit: "Fee"},
          {name: "Back-end Developer", unit: "Fee"},
          {name: "Back-end Developer (off-shore)", unit: "Fee"},
          {name: "Creative Technologist", unit: "Fee"},
          {name: "Front-end Lead Developer", unit: "Fee"},
          {name: "Front-end Developer", unit: "Fee"},
          {name: "Front-end Developer (off-shore)", unit: "Fee"},
          {name: "HTML Coder", unit: "Fee"},
          {name: "HTML Coder (off-shore)", unit: "Fee"},
          {name: "Webmaster", unit: "Fee"},
          {name: "Webmaster (off-shore)", unit: "Fee"},
          {name: "QA Manager", unit: "Fee"},
          {name: "QA Lead", unit: "Fee"},
          {name: "QA Tester", unit: "Fee"},
          {name: "QA Lead (off-shore)", unit: "Fee"},
          {name: "QA tester (off-shore)", unit: "Fee"},
          {name: "Agent Commission (Serv.)", unit: "Fee"},
          {name: "Agent Commission", unit: "Fee"},
          {name: "Social Contributions (Serv.)", unit: "Fee"},
          {name: "Social Contributions", unit: "Fee"},
        ]
      },
    ]
  },
  {
    id: "F",
    name: "F. POST-PRODUCTION PRINT",
    subs: [
      {
        name: "26. Supervision",
        items: [
          {name: "Project Manager", unit: "Day"},
        ]
      },
      {
        name: "27. Execution",
        items: [
          {name: "Graphic Designer", unit: "Fee"},
          {name: "Single-page Master", unit: "Fee"},
          {name: "Double-page Master", unit: "Fee"},
          {name: "Single-page Declination", unit: "Fee"},
          {name: "Double-page Declination", unit: "Fee"},
          {name: "Poster Master", unit: "Fee"},
          {name: "Poster Declination", unit: "Fee"},
          {name: "Large Format Poster Master", unit: "Fee"},
          {name: "Large Format Poster Declination", unit: "Fee"},
          {name: "BTL Master Small Posters/Flags/Wind. Displays/Easel, etc.", unit: "Fee"},
          {name: "BTL Declin. Small Posters/Flags/Wind. Displays/Easel, etc.", unit: "Fee"},
          {name: "10x21 cm or 21x10 cm Edition", unit: "Fee"},
          {name: "14.5x21 cm or 21x14.5 cm Edition", unit: "Fee"},
          {name: "29.7x42 cm or 42x29.7 cm Edition", unit: "Fee"},
          {name: "Superior Format", unit: "Fee"},
          {name: "Die-cut Shape", unit: "Fee"},
          {name: "Changes Above 2 Rounds of Revisions", unit: "Fee"},
          {name: "Tracing", unit: "Fee"},
          {name: "Layout", unit: "Fee"},
        ]
      },
      {
        name: "28. Engraving",
        items: [
          {name: "Graphic Designer", unit: "Fee"},
          {name: "Press", unit: "Fee"},
          {name: "Poster", unit: "Fee"},
          {name: "BTL Master Small Posters/Flags/Wind. Displays/Easel, etc.", unit: "Fee"},
          {name: "BTL Declin. Small Posters/Flags/Wind. Displays/Easel, etc.", unit: "Fee"},
          {name: "BTL (Below The Line) Edition", unit: "Fee"},
          {name: "Tracing", unit: "Fee"},
        ]
      },
      {
        name: "29. Execution Retouching",
        items: [
          {name: "Retoucher", unit: "Fee"},
          {name: "Technical Retouching", unit: "Fee"},
          {name: "Creative Retouching", unit: "Fee"},
        ]
      },
      {
        name: "30. Delivery",
        items: [
          {name: "Traffic", unit: "Fee"},
          {name: "FTP", unit: "Fee"},
          {name: "Unarchiving", unit: "Fee"},
          {name: "Website Deployment", unit: "Fee"},
          {name: "Media Planning", unit: "Fee"},
          {name: "Courier in Paris", unit: "Fee"},
          {name: "Courier in the Nearby Suburbs", unit: "Fee"},
          {name: "Car Courier", unit: "Fee"},
          {name: "Courier +15km", unit: "Fee"},
        ]
      },
      {
        name: "31. Proof",
        items: [
          {name: "Layout Artist", unit: "Fee"},
          {name: "Layout", unit: "Fee"},
        ]
      },
      {
        name: "32. Epsons",
        items: [
          {name: "Graphic Designer", unit: "Fee"},
          {name: "Epson <= A4", unit: "Fee"},
          {name: "Epson", unit: "Fee"},
          {name: "Epson > A2", unit: "Fee"},
          {name: "Epson Printer", unit: "Fee"},
        ]
      },
      {
        name: "33. Miscellaneous",
        items: [
          {name: "Project Manager", unit: "Fee"},
          {name: "Graphic Designer", unit: "Fee"},
          {name: "Retoucher", unit: "Fee"},
          {name: "Traffic Manager", unit: "Fee"},
          {name: "A4 Board", unit: "Fee"},
          {name: "A3 Board", unit: "Fee"},
          {name: "A2 Board", unit: "Fee"},
          {name: "Board > A2", unit: "Fee"},
          {name: "Graphic Designer's Rush", unit: "Fee"},
          {name: "Project Manager/Traffic Manager's Rush", unit: "Fee"},
          {name: "Unarchiving", unit: "Fee"},
          {name: "MAD Opera", unit: "Fee"},
          {name: "MAD Share", unit: "Fee"},
          {name: "Agent Commission (Serv.)", unit: "Fee"},
          {name: "Agent Commission", unit: "Fee"},
          {name: "Social Contributions (Serv.)", unit: "Fee"},
          {name: "Social Contributions", unit: "Fee"},
        ]
      },
    ]
  },
  {
    id: "G",
    name: "G. GLOBAL DELIVERY SERVICE",
    subs: [
      {
        name: "34. GO Global Adaptation/Localisation",
        items: [
          {name: "Translation/Transcreation", unit: "Fee"},
          {name: "International VO Recording", unit: "Fee"},
          {name: "Sound Mix (no creation nor edit)", unit: "Fee"},
          {name: "Video Adaptation", unit: "Fee"},
          {name: "Legal Clearance", unit: "Fee"},
        ]
      },
      {
        name: "35. Air Copy",
        items: [
          {name: "Air Copy Manager", unit: "Day"},
          {name: "Pivot File HD/spot", unit: "Fee"},
          {name: "Pivot File HD/spot (3 spots LN)", unit: "Fee"},
          {name: "Pivot File HD/spot (4 spots MS)", unit: "Fee"},
          {name: "ARPP 1 Spot (classic 48H)", unit: "Unit"},
          {name: "ARPP 1 Spot 3 LN (classic 48H)", unit: "Unit"},
          {name: "ARPP 1 Spot 4 MS (classic 48h)", unit: "Unit"},
          {name: "ARPP 1 Spot (express 24h)", unit: "Unit"},
          {name: "ARPP 1 Spot 3 LN (express 24h)", unit: "Unit"},
          {name: "ARPP 1 Spot 4 MS (express 24h)", unit: "Unit"},
          {name: "ARPP 1 Spot (premium 1H)", unit: "Unit"},
          {name: "ARPP 1 Spot 3 LN (premium 1H)", unit: "Unit"},
          {name: "ARPP 1 Spot 4 MS (premium 1H)", unit: "Unit"},
          {name: "Load MPEG 2/H264 on ARPP (1 spot)", unit: "Unit"},
          {name: "Load MPEG 2/H264 on ARPP(3 spots ML)", unit: "Fee"},
          {name: "Load MPEG 2/H264 on ARPP(4 spots MS)", unit: "Fee"},
          {name: "Deaf/Impaired Hearings/Titles (spot)", unit: "Unit"},
          {name: "Deaf/Impaired Hearings/Titles (spot/1MS)", unit: "Unit"},
          {name: "Deaf/Impaired Hearings/Titles. (declin., re-edit.)", unit: "Unit"},
          {name: "Deaf/Impaired Hearings/Titles (add MS)", unit: "Unit"},
          {name: "Audio Description (spot)", unit: "Unit"},
          {name: "Audio Description (spot/1MS)", unit: "Unit"},
          {name: "Audio Description (adaptation, re-editing)", unit: "Unit"},
          {name: "Audio Description (MS sup.)", unit: "Unit"},
          {name: "Demat. 1 Spot HD/Delivery Point", unit: "Unit"},
          {name: "Demat. 1 Spot HD/Delivery Point (3LN)", unit: "Unit"},
          {name: "Demat. 1 Spot HD/Delivery Point (4MS)", unit: "Unit"},
          {name: "Demat. Exp. 1 Spot HD/Delivery Point", unit: "Unit"},
          {name: "Demat. Exp. 1 Spot HD/Delivery Point (3LN)", unit: "Unit"},
          {name: "Demat. Exp. 1 Spot HD/Delivery Point (4MS)", unit: "Unit"},
          {name: "MPEG 1/MPEG 2/H264 Control (spot)", unit: "Unit"},
          {name: "MPEG 1/MPEG 2/H264 Control (3 spots LN)", unit: "Unit"},
          {name: "MPEG 1/MPEG 2/H264 Control (4 spots MS)", unit: "Unit"},
        ]
      },
      {
        name: "36. Delivery Upload Platform",
        items: [
          {name: "Toolkit + Upload Client Platform/film", unit: "Fee"},
          {name: "Toolkit + Upload Client Platform/film >10 films", unit: "Fee"},
          {name: "Toolkit + Upload Client Platform/film >30 films", unit: "Fee"},
          {name: "Upload Platform/film with Taxonomy", unit: "Fee"},
          {name: "Upload Platform/film without Taxonomy", unit: "Fee"},
          {name: "Upload Platform/film >10 films with Taxonomy", unit: "Fee"},
          {name: "Upload Platform/film >10 without Taxonomy", unit: "Fee"},
          {name: "Upload Platform/film >30 films with Taxonomy", unit: "Fee"},
          {name: "Upload Platform/film >30 without Taxonomy", unit: "Fee"},
        ]
      },
    ]
  },
  {
    id: "H",
    name: "H. MEALS, HOTELS & PER DIEM",
    subs: [
      {
        name: "37.1. Meals",
        items: [
        ]
      },
      {
        name: "Prep, Wrap",
        items: [
          {name: "Prep & Technical Recces", unit: "Unit"},
          {name: "Pre-light", unit: "Unit"},
          {name: "Setup & constr.", unit: "Unit"},
          {name: "Craft (drinks & Snacks)", unit: "Unit"},
          {name: "Incidentals (room Service)", unit: "Unit"},
          {name: "Catering Equipment", unit: "Unit"},
          {name: "Barnum Supplement for Canteen", unit: "Unit"},
        ]
      },
      {
        name: "Shooting",
        items: [
          {name: "Shooting Crew", unit: "Unit"},
          {name: "Talent", unit: "Unit"},
          {name: "Extras, Children & Other Talents", unit: "Unit"},
          {name: "Agency/Client", unit: "Unit"},
          {name: "Craft (drinks & Snacks)", unit: "Unit"},
          {name: "Incidentals (room Service)", unit: "Unit"},
          {name: "Catering Equipment", unit: "Unit"},
          {name: "Barnum Supplement for Canteen", unit: "Unit"},
        ]
      },
      {
        name: "Post-production",
        items: [
          {name: "Meals (global)", unit: "Unit"},
        ]
      },
      {
        name: "37.2. Hotels",
        items: [
        ]
      },
      {
        name: "Prep, Wrap",
        items: [
          {name: "Technical Recces", unit: "Unit"},
          {name: "Director/PPM", unit: "Unit"},
          {name: "Executive Producer/PPM", unit: "Unit"},
          {name: "Crew", unit: "Unit"},
        ]
      },
      {
        name: "Shooting",
        items: [
          {name: "Director", unit: "Nights"},
          {name: "Line Producer", unit: "Nights"},
          {name: "Executive Producer", unit: "Nights"},
          {name: "Director of Photography", unit: "Nights"},
          {name: "1st Ass. Director", unit: "Nights"},
          {name: "Crew", unit: "Nights"},
          {name: "Talent", unit: "Nights"},
          {name: "Extras, Children & Others", unit: "Nights"},
          {name: "VFX Supervisor", unit: "Nights"},
          {name: "Post Producer", unit: "Nights"},
          {name: "Agency/Client", unit: "Nights"},
        ]
      },
      {
        name: "Post-production",
        items: [
          {name: "Director", unit: "Nights"},
          {name: "Post Producer", unit: "Nights"},
          {name: "Supervisor", unit: "Nights"},
          {name: "Editor", unit: "Nights"},
          {name: "Post-production Crew", unit: "Nights"},
          {name: "Producer", unit: "Nights"},
          {name: "Agency/Client", unit: "Nights"},
        ]
      },
      {
        name: "37.3. Per Diem",
        items: [
        ]
      },
      {
        name: "Prep, Wrap",
        items: [
          {name: "Technical Recces", unit: "Unit"},
          {name: "Director/PPM", unit: "Unit"},
          {name: "Executive Producer/PPM", unit: "Unit"},
          {name: "Crew", unit: "Unit"},
        ]
      },
      {
        name: "Shooting",
        items: [
          {name: "Director", unit: "Unit"},
          {name: "Line Producer", unit: "Unit"},
          {name: "Executive Producer", unit: "Unit"},
          {name: "Director of Photography", unit: "Unit"},
          {name: "1st Ass. Director", unit: "Unit"},
          {name: "Crew", unit: "Unit"},
          {name: "Talent", unit: "Unit"},
          {name: "Extras, Children & Others", unit: "Unit"},
          {name: "VFX Supervisor", unit: "Unit"},
          {name: "Post Producer", unit: "Unit"},
          {name: "Agency/Client", unit: "Unit"},
        ]
      },
      {
        name: "Post-production",
        items: [
          {name: "Director", unit: "Unit"},
          {name: "Post Producer", unit: "Unit"},
          {name: "Supervisor", unit: "Unit"},
          {name: "Editor", unit: "Unit"},
          {name: "Post-production Crew", unit: "Unit"},
          {name: "Producer", unit: "Unit"},
          {name: "Agency/Client", unit: "Unit"},
        ]
      },
    ]
  },
  {
    id: "I",
    name: "I. TRAVELS",
    subs: [
      {
        name: "38.1. Prep, Wrap",
        items: [
          {name: "Airport & Train Stations Transfers", unit: "Unit"},
          {name: "Director/PPM", unit: "Unit"},
          {name: "Executive Producer/PPM", unit: "Unit"},
          {name: "Others/PPM", unit: "Unit"},
          {name: "Director", unit: "Unit"},
          {name: "Producer", unit: "Unit"},
          {name: "Crew", unit: "Unit"},
        ]
      },
      {
        name: "38.2. Shooting",
        items: [
          {name: "Airport & Train Stations Transfers", unit: "Unit"},
          {name: "Director", unit: "Unit"},
          {name: "Line Producer", unit: "Unit"},
          {name: "Executive Producer", unit: "Unit"},
          {name: "Director of Photography", unit: "Unit"},
          {name: "1st Ass. Director", unit: "Unit"},
          {name: "Crew", unit: "Unit"},
          {name: "Talent", unit: "Unit"},
          {name: "Extras, Children & Others", unit: "Unit"},
          {name: "VFX Supervisor", unit: "Unit"},
          {name: "Post Producer", unit: "Unit"},
          {name: "Agency/Client", unit: "Unit"},
        ]
      },
      {
        name: "38.3. Post-production",
        items: [
          {name: "Airport & Train Stations Transfers", unit: "Unit"},
          {name: "Director", unit: "Unit"},
          {name: "Post Producer", unit: "Unit"},
          {name: "Supervisor", unit: "Unit"},
          {name: "Editor", unit: "Unit"},
          {name: "Post-production Crew", unit: "Unit"},
          {name: "Producer", unit: "Unit"},
          {name: "Agency/Client", unit: "Unit"},
        ]
      },
    ]
  },
  {
    id: "J",
    name: "J. INSURANCES",
    subs: [
      {
        name: "(Excl. Insurances Equipment)",
        items: [
          {name: "Negative & Other Medias (Serv.)", unit: "Fee"},
          {name: "Civil Risk Insurance (Serv.)", unit: "Fee"},
          {name: "No Show 3 persons (Serv.)", unit: "Fee"},
          {name: "Other Insurance 1 (Serv.)", unit: "Fee"},
          {name: "Other Insurance 2 (Serv.)", unit: "Fee"},
          {name: "Negative & Other medias", unit: "Fee"},
          {name: "Civil Risk Insurance", unit: "Fee"},
          {name: "No Show 3 persons (except Covid)", unit: "Fee"},
          {name: "Other Insurance 1", unit: "Fee"},
          {name: "Other Insurance 2", unit: "Fee"},
          {name: "Multi-risk Insurance", unit: "Fee"},
          {name: "No Show Vehicle", unit: "Fee"},
          {name: "All Risks Vehicle", unit: "Fee"},
          {name: "Car Insurance", unit: "Fee"},
          {name: "Special Insurance", unit: "Fee"},
          {name: "Repatriation Insurance", unit: "Fee"},
          {name: "Hard Drives Insurance", unit: "Fee"},
          {name: "Insurance Covid", unit: "Fee"},
          {name: "Weather Day Fee", unit: "Fee"},
          {name: "Observer", unit: "Fee"},
        ]
      },
    ]
  },
  {
    id: "K",
    name: "K. SOCIAL CONTRIBUTIONS",
    subs: [
      {
        name: "39. Social Contributions Exe",
        items: [
          {name: "Design & Coordination", unit: "%"},
          {name: "Pre-Production & Shooting Crew", unit: "%"},
          {name: "Talent", unit: "%"},
          {name: "Director", unit: "%"},
          {name: "Production Photo", unit: "%"},
          {name: "Post-Production Image", unit: "%"},
          {name: "Post-Production Sound & Music", unit: "%"},
          {name: "Production Digital", unit: "%"},
          {name: "Post-Production Print", unit: "%"},
        ]
      },
      {
        name: "Social Contributions France",
        items: [
          {name: "Design & Coordination", unit: "%"},
          {name: "Pre-Production & Shooting Crew", unit: "%"},
          {name: "Talent", unit: "%"},
          {name: "Director", unit: "%"},
          {name: "Production Photo", unit: "%"},
          {name: "Post-Production Image", unit: "%"},
          {name: "Post-Production Sound & Music", unit: "%"},
          {name: "Production Digital", unit: "%"},
          {name: "Post-Production Print", unit: "%"},
        ]
      },
    ]
  },
];
